### ISSUE TITLE
Mutex failure on linux

### ISSUE THREAD

**Issue by rconde01** [oleg-shilo/cs-script#10]
As of mono 4.4 there's no way to use named mutexes on linux (it used to be disabled by default but could be enabled using MONO_ENABLE_SHM). The cs-script caching mechanism depends on this functionality so therefore is broken.

Reference: https://bugzilla.xamarin.com/show_bug.cgi?id=39836

Unfortunately, it doesn't appear .NET Core will help any time soon:

https://github.com/dotnet/coreclr/issues/1237

**Comment by oleg-shilo** [comment]
This is  quite a shocker for me. I couldn't believe that such a fundamental synchronization mechanism as Mutex doesn't exhibit the same behavior on all supported OSs. But the links rconde01 provided do not lie.
If you cannot trust Mutex then what can we trust at all? :)

Anyway, I considered implementing some poor-man equivalent based on "file-open-for-write" approach. I even prepared the whole infrastructure for it, but... Aww man, it looked so ugly. I just could commit that atrocity to the existing solution and decided to postpone the change. Particularly because neither of the links categorically stated that the functionality will never be fixed/implemented.

I do not close this issue but just put it on hold.    

In a mean time most of the concurrency problems on Linux (locking compiled script) can be solved by executing the script as "in-memory" assembly. The mode can be engaged with
- command line arg  `-inmem` 
- script embedded directive `//css_args -inmem;`

The `-inmem` is an extremely useful approach as it solves many problems (in a very straight forward way) and the only reason why it is not default is that the loaded script assembly will not have the file associated with it. While this is absolutely appropriate in 99% of cases sometimes (e.g. complicated Reflection scenarios) knowing the assembly file is'n optional. For such cases use "script reflection" technique described [here](https://github.com/oleg-shilo/cs-script/wiki/CS-Script-Runtime-Environment-%28script-reflection%29).  
 
These are the new features that have been implemented specifically to address the problem described in this issue.

**Comment by oleg-shilo** [comment]
After some digging I found that practically everyone facing the same problem ended up with "file lock" based solution. It doesn't provide the 100% Mutex compatible functionality but it does mimic it reasonably well. 

The latest release contains the required changes and now CS-Script on Linux should have all required concurrency control working as expected. Though using command line arg `-inmem` is arguably a preferred option and should be used by default.
____
Fixed (Release v3.16).
Thank you. 
https://github.com/oleg-shilo/cs-script/releases/tag/v3.16.0.0
https://chocolatey.org/packages/cs-script/3.16.0.0

**Comment by rconde01** [comment]
FYI:
https://github.com/dotnet/coreclr/pull/5030/files

**Comment by oleg-shilo** [comment]
Txs. Good to know. 
Though it does not help with Mono. Thus is my understanding that .NET Core and Mono do not share that part of the code that you shared.

**Comment by rconde01** [comment]
No - but it helps the dotnet core version, and...if you want, you can just integrate their implementation.

**Comment by oleg-shilo** [comment]
Currently dotnet core version of CS-Script relies on Roslyn engine only. And using this engine implies no script caching and no need for system wide synchronization.  `Mutex` is only used by the CodeDOM engine. This is correct regardless of the nature of the host application (.NET or Mono).

Meaning that  dotnet core version of CS-Script is immune to the Mutex problem.

However you are absolutely right, if dotnet core version ever evolve to support script caching then indeed Mutex support will become essential.

**Comment by rconde01** [comment]
What if the script itself needs a global mutex?

**Comment by oleg-shilo** [comment]
Yep, then the outcome will depend on the host runtime: 
```
.NET Core/Win    - OK
.NET Core/Linux  - OK
.NET             - OK      
Mono/Win         - OK
Mono/Linux       - OK (local Mutex) and Fail (system-wide Mutex) 
```

**Comment by rconde01** [comment]
Duh...right...sorry
