### ISSUE TITLE
Dependencies are not loaded after AppPool recycle

### ISSUE THREAD

**Issue by veremenko-y** [oleg-shilo/cs-script#111]
I use simple code to load and run script in my ASP.NET application. `CSScript.LoadCode(script).CreateObject("*")`. It does depend on the assembly it executes in. And it works just fine, until AppPool is recycled.
After that it returns:
```
C:\\Temp\\CSSCRIPT\\dynamic\\816be14d-bc79-4ccf-99ed-aa62b63b922f.tmp(5,7): error CS0246: The type or namespace name '<Lib>' could not be found (are you missing a using directive or an assembly reference?)
```

I tried to disable cache, but it does not seem to help.

**Comment by oleg-shilo** [comment]
The cache actually supposed to make things simpler in the scenarios like this one. Though if the cached model was designed with the idea in mind that the host assembly will never be disposed/unloaded. Definitely not your case.

There can be some parasitic dependencies since the all host dependency assemblies are loaded.

I suggest you do a few things:
- Disable caching - just to be in full control:
  `CSScript.CacheEnabled = false;`
- Disable automatic assembly referencing - the same reason (full control):
  `CSScript.ShareHostRefAssemblies = false;`
- Reference all your assemblies explicitly.
- Implement your caching by yourself

Something like this:
```C#
static string script_asm;
static string host_asm = Assembly.GetExecutingAssembly().Location;

static void test_method()
{
    var master_script = @"using System;
                            public class Script
                            {
                                public void SayHello(string greeting)
                                {
                                    Console.WriteLine(greeting);
                                }
                            }";


    if (script_asm == null)
        script_asm = CSScript.CompileCode(master_script, host_asm);

    dynamic script = Assembly.LoadFrom(script_asm)
                                .CreateObject("*");

    script.SayHello("test");
}

static void Issue111()
{
    CSScript.CacheEnabled = false;
    CSScript.ShareHostRefAssemblies = false;

    for (int i = 0; i < 3; i++)
    {
        AppDomain appPool = AppDomain.CurrentDomain.Clone();
        appPool.Execute(test_method);
        appPool.Unload();
    }
}
```

**Comment by oteinone** [comment]
We might have a similar problem in our ASP.NET application. Our implementation is at the moment very simple:

`return CSScript.Evaluator.LoadMethod<T>(scriptstring);`

For some reason after a scheduled app pool recycle we get a 

> CS0246: The type or namespace name `CalculateServiceOperations' could not be found

 error but manually recycling the app pool everything works ok.

Is there any way to make sure that the assemblies are available for the script?

**Comment by oleg-shilo** [comment]
Your case is different. @veremenko-y used [CSScript.Native](https://github.com/oleg-shilo/cs-script/wiki/Choosing-Compiler-Engine#csscriptnative) compiling engine:
```
CSScript.LoadCode(script).CreateObject("*")
````
You are using newer interface [CSScript.Evaluator](https://github.com/oleg-shilo/cs-script/wiki/Choosing-Compiler-Engine#csscriptevaluator)
 ```
CSScript.Evaluator.LoadMethod<T>(code)
```
CSScript.Evaluator by default uses Mono evaluator. I suggest you try to use different evaluator engine:
```
CSScript.EvaluatorConfig.Engine = EvaluatorEngine.CodeDom;
// or
CSScript.EvaluatorConfig.Engine = EvaluatorEngine.Roslyn;
```

Or even CSScript.Native.

However, regardless what engine you are using, if your script has dependency on the assembly that hase been recycled/disposedit will fail during the execution. Even more... The problem has nothing to do with the scripting. If you execute a completely compiled assembly, which happens to reference another assembly that is already disposed (recycled) you will have the same problem.

The solution is the prevention of the offending assembly from being recycled/disposed. The chances are that you have very little control over it.

If it is the case then you have no choice but to execute the script everytime you need to do the call instead of reusing the script execution object returned by LoadMethod.

Though I am still puzzled about the fact that your script is referencing something that it arguebly does not need.

Ensure that you do not reference ALL loaded assemblies: 
```
CSScript.EvaluatorConfig.RefernceDomainAsemblies = false
``` 
It is a the default mode that is rather very convenient. But may be it just does not fit the ASP.NET scenario.
