### ISSUE TITLE
csws.exe shim created by chocolatey opens console window when running script

### ISSUE THREAD

**Issue by ivanatpr** [oleg-shilo/cs-script#112]
When you install cs-script via chocolatey it'll put the cs-script executables in C:\ProgramData\chocolatey\lib\cs-script\tools\cs-script and chocolatey also creates executable shims that are put in your PATH under "C:\ProgramData\chocolatey\bin". However the shim created for csws.exe seems to treat it as a console application, briefly opening a console window when a script runs. (note that your chocolatey root directory may be different from mine, but he relative paths should be the same)

I'm not sure how it all works but the documentation for the utility for generating those shims seems to have an [--shimgen-gui](https://github.com/chocolatey/shimgen) option to handle non-console executables.

Note that CS-Script also adds itself to the system PATH, so you might never encounter this issue unless the chocolately bin directory ends up before the CS-Script entries in your PATH. This issue only surfaced for me after I'd cleaned up and reordered some entries my PATH, so I think it was my own fault, but it was *extremely* confusing to track down what was happening. I reordered the entries in my PATH and the issue went away. So, definitely a low priority issue but I at the very least I wanted to post this in case anybody else ran into it.

Steps to recreate:

1. Hit Win+R and execute 'C:\ProgramData\chocolatey\lib\cs-script\tools\cs-script\csws.exe C:\path\to\script.cs' -> Script runs, No console window opens
2. Hit Win+R and execute  'C:\ProgramData\chocolatey\bin\csws.exe C:\path\to\script.cs' -> Script runs, console window flashes while script is running

**Comment by oleg-shilo** [comment]
Thank you. Very interesting.

I deliberately add CS-Script binaries in the PATH to avoid the problems like that. Saying that, I definitely prefer to fix this problem.

Though I am finding it close to impossible to customize shim generation for downloaded packages. I couldn't find any information on customizing shiming for individual items from a zip package. This is the Chocolatey API that is used for the CS-Script installation:
```PS
Install-ChocolateyZipPackage "$packageName" "$url" "$installDir" -checksum $checksum -checksumType $checksumType
```
Unfortunately  [Install-ChocolateyZipPackage API](https://chocolatey.org/docs/helpers-install-chocolatey-zip-package) does not offer any options for shiming. None at all!

I just don't see how this can be achieved without reinventing (a complete rewrite of) `ChocolateyZipPackage`. Am I missing something here?

**Comment by oleg-shilo** [comment]
Now I am just thinking... Would it be just easier to delete `csws.exe` shim after the install?

**Comment by ivanatpr** [comment]
It looks like chocolatey provides a means to mark an executable as a gui app as well as to exclude it from being shimmed altogether. See [here](https://chocolatey.org/docs/create-packages#how-do-i-set-up-shims-for-applications-that-have-a-gui) and [here](https://chocolatey.org/docs/create-packages#how-do-i-exclude-executables-from-getting-shims).

**Comment by oleg-shilo** [comment]
Yeah, I looked at that and it only confirms what I was afraid of - Chocolatey has no solution for this problem. I'll elaborate.
 
Chocolatey offers two packaging mechanisms:
1. All application files are embedded into the package.
2. All application files are downloaded as zip file from the special URL at install time.

The first mechanism indeed allows precise control of shiming. However the second one (arguably the most common) has no shiming customization whatsoever.

CS-Script package is based on the second model. The whole package definition is expressed in a single line:
```xml
<files>
    <file src="tools\chocolateyInstall.ps1" target="tools\chocolateyInstall.ps1" />
</files>
```  
Where the PS script:
```PS
Install-ChocolateyZipPackage "$packageName" "$url" "$installDir" ...
```
And the problem is that `Install-ChocolateyZipPackage` does unconditional shiming. 
For all practical purposes I would even prefer `Install-ChocolateyZipPackage` to allow unconditional disabling of shiming at all.

Anyway, I will look into it and add an extra post-install step where the shim(s) will be either deleted or regenerated. 

Thank you for bringing the matter up.

**Comment by oleg-shilo** [comment]
After rereading the links you have provided I concluded that having a post install step is actually the way Chocolaty expects packages to control shiming. Will give it a try. Txs.

**Comment by oleg-shilo** [comment]
Done. 
At least in https://github.com/oleg-shilo/cs-script/releases/tag/v3.28.9.0
