### ISSUE TITLE
chocolaty install issue

### ISSUE THREAD

**Issue by dbenson2000** [oleg-shilo/cs-script#118]
When installing cs-script through chocolaty, I'm getting an error about VBCSCompiler, even though this is present. I'm running inside an administrator command prompt on Windows 10 Enterprise, 1803. I have Visual Studio 2017 Professional 15.7.3 with C# tools

choco install cs-script
Chocolatey v0.10.11
Installing the following packages:
cs-script
By installing you accept licenses for the packages.
Progress: Downloading cs-script 3.28.4.0... 100%
...
C:\ProgramData\chocolatey\lib\cs-script\tools
Cannot find a process with the name "VBCSCompiler". Verify the process name and call the cmdlet again.
...
ShimGen has successfully created a shim for VBCSCompiler.exe
...
The install of cs-script was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\cs-script\tools'

Ignoring the error and attempting to right click a .cs file results in 
![image](https://user-images.githubusercontent.com/15785824/42526796-1a245ff6-8434-11e8-9f97-29d99acb430d.png)
[chocolatey.log](https://github.com/oleg-shilo/cs-script/files/2181484/chocolatey.log)

**Comment by oleg-shilo** [comment]
There are two problems (at least).

> Cannot find a process with the name "VBCSCompiler". Verify the process name and call the cmdlet again.

This is the PowerShell output within Choco installation. It is triggered by this PS code:
```PS
    try
    {
        Stop-Process -Name "VBCSCompiler"
    } catch
    {
    }
```
I am guessing that `Stop-Process` prints the error info regardless the fact that it is inside of `try...catch`. The "error" is not an error at all as the purpose of that code was to stop 'VBCSCompiler' if it is running.

> ...attempting to right click a .cs file results in...

It's hard to say but the script , which composes the VS project on-fly cannot find either clicked file or some of its dependencies.

I suggest you debug the `debugVS15.0.cs` script and see what is going wrong. For that you will need to add `//x` suffix to your script launching command:

![image](https://user-images.githubusercontent.com/16729806/42570024-dc6fec52-8555-11e8-82b1-8d6c662c1241.png)

Do the right click again and `debugVS15.0.cs` will start and prompt you to attach the debugger. Then you know what to do...

**Comment by dbenson2000** [comment]
Not sure why, but the debugger doesn't launch. Reverted to old school debugging and can see that the path to the generated solution file is valid. I can run the generated solution file and debug my script so, while not elegant, gets the job done.

I'm asking a colleague with a similar configuration to try and reproduce.

**Comment by ShawnPierce** [comment]
Found my issue, my laptop McAfee rules are not configured by me but, it's McAfee 

ran EXPLORER.EXE, which tried to access C:\PROGRAMDATA\CS-SCRIPT\SHELLEXTENSION\3.28.4.0\CS-SCRIPT, violating the rule "Suspicious Double File Extension Execution", and was blocked. For information about how to respond to this event, see KB85494.

Looking to modify that rule but, hopefully, this helps you guys. Thank you..

**Comment by oleg-shilo** [comment]
Excellent. Thank you for the update. 
To be honest it's not the first time antiviruses are causing the problems. Though every time it is from the unexpected direction.

**Comment by dbenson2000** [comment]
My colleague had the same error with VS2017, but VS2015 didn't cause the same issue. Not sure how that would be affected by antivirus

**Comment by oleg-shilo** [comment]
The VS is very simple under the hood. It is tricky to set up the shell extensions but the integration itself is quite simple. One can easily test it:
```PS
C:\> csws debug2015 "D:\dev\client\client.cs"
```
The code above will open `client.cs` in VS2015 in debug project.

And if you add `//x` at the end you can debug 'debug2015.cs' script by attaching the debugger when you are prompted.

If/when you are happy with your 'debug2015.cs'  you can wrap it into a simplified (non-COM) shell extension via registry:
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\VisualStudio.cs.14.0\shell\Open in VS2017\Command]
@="\"C:\\ProgramData\\chocolatey\\lib\\cs-script\\tools\\cs-script\\csws.exe\" debug2015 \"%1\""
```

And this is the final result: 
![image](https://user-images.githubusercontent.com/16729806/42686660-f12233aa-86d9-11e8-9c06-1e7b6aa579c4.png)

**Comment by benblo** [comment]
I had a similar issue with `Cannot find a process with the name "VBCSCompiler".` (not sure if I should have open a new issue or if recycling this one is ok), while install with choco with cmd.exe in admin mode, Window 10. I tried turning off Windows Defender, same error.
I've attached my [install log](https://github.com/oleg-shilo/cs-script/files/2851518/install-cmd.log), including the `cscs` report, which has proper install dir etc.

I tried uninstalling and reinstalling with PowerShell ([install-powershell.log](https://github.com/oleg-shilo/cs-script/files/2851539/install-powershell.log)): I didn't have the VBCSCompiler error this time, but I still don't have explorer right click integration :(.

I tried your tip of running `csws debug2017 "C:\Work\hello.cs"` (my test script), and it worked fine, it launched VS and I was able to run the script, add a breakpoint etc.

... now I re-read the thread, apparently the VBCSCompiler error doesn't matter... then what I am missing, how do I get explorer integration like seen [here](http://www.csscript.net/Images/menu.png)?

**Comment by oleg-shilo** [comment]
Correct. VBCSCompiler error doesn't matter during the installation. It is a report about failing attempt to stop Roslyn services. They need to be stopped in order to register CS-Script COM-based shell-extensions. Failure to stop Roslyn may or may not affect you ability to run Roslyn compiled scripts. It all depends. But usually it doe snot affect anything. 

Though in your case you are interested in setting up non-COM shell extension and they are not a part choco installation. It needs to be setup manually.

The following key in registry will do the trick:
```
[HKEY_CLASSES_ROOT\VisualStudio.cs.14.0\shell\Open in VS2017\Command]
@="\"C:\\ProgramData\\chocolatey\\lib\\cs-script\\tools\\cs-script\\cscs.exe\" \"%1\""
```   
![image](https://user-images.githubusercontent.com/16729806/52683122-f3e4c700-2f95-11e9-8867-f8964e82fa29.png)

**Comment by benblo** [comment]
So I tried to add the regkey, but I still don't see anything in the context menu:
![image](https://user-images.githubusercontent.com/574187/52786869-57392c80-305c-11e9-854f-e8b0ab824264.png)
I'm a bit suspicious too, because I didn't even have a VisualStudio.cs.14.0 registry folder until now, shouldn't I be installing to VisualStudio.cs.f030b1b1?

TBH I find this all a bit voodoo. Since then I found css_config.exe, and the "configure shell extension" tool... isn't this supposed to handle this?

**Comment by oleg-shilo** [comment]
You are right, `css_config.exe` supposed to handle the registry settings so no manual editing is required. Though MS has changed the original VS deployment approach and effectively broke the `css_config.exe` algorithm for the latest VS completely.

Originally any VS20?? installations had the file right-click extensions defined as  `VisualStudio.cs.??.0` registry key. So `css_config.exe` could do the registry update during the installation. 

Since then MS changed the approach (staring from ~VS2017) and now the registry key is named like this: `VisualStudio.cs.<random prefix>`. Meaning that creating `VisualStudio.cs.14.0` does not produce the desired outcome.

That's why one needs to create the registry key manually as the random reg key name prefix is unique for the target PC and cannot be deterministically discovered by the `css_config.exe` during setup.

I am marking the issue as an "enhancement" and will see if there is an opportunity to support the new approach as well.

**Comment by oleg-shilo** [comment]
It turns out that there is already support for ignoring empty directories. Though it needs to be done as an explicit wild card resolving step: 

```C#
       . . .
       project.GUID = new Guid("6f330b47-2577-43ad-9095-1561ba25889b");
       project.ResolveWildCards(ignoreEmptyDirectories: true);

       project.BuildMsi();
```

And in the next release a new global setting will be introduced to control the default believer in more intuitive way:

```C#
       Compiler.AutoGeneration.IgnoreWildCardEmptyDirectories = true;

       project.GUID = new Guid("6f330b47-2577-43ad-9095-1561ba25889b");
       project.BuildMsi();

```
