### ISSUE TITLE
Working with xaml

### ISSUE THREAD

**Issue by uwbwsvd** [oleg-shilo/cs-script#119]
Notepad++ v7.5.7   (32-bit)
cs 1.7.13 cscs engine 3.28.4.0
I tried this
http://csscript.net/help/wpf.html
and get the error:
hello.xaml(1,1): error CS0116: Ein Namespace kann nicht direkt Member, wie z.B. Felder oder Methoden, enthalten.
Is there perhaps something wrong with encoding?

**Comment by oleg-shilo** [comment]
The sample described there may not longer work as it was designed and implemented for .NET 3.5. The problem is that the sample relied on the custom compiler/code provider (MSBuild), which may not work the same way on the other .NET runtime (e.g. .NET 4.5+).

It is recommended when running CS-Script scripts for WPF to load XAML dynamically. This way there is no need for a custom compiler (MSBuild). The sample that demonstrates the technique can be found here: [DynamicWPF](https://github.com/oleg-shilo/cs-script/tree/master/Source/deployment/samples/WPF/DynamicWPF).

I have just updated  http://csscript.net/help/wpf.html to reflect the changes in the XAML support.
