### ISSUE TITLE
ReferenceAssembliesFromCode returning dlls from GAC_32 when host is running as AnyCPU.

### ISSUE THREAD

**Issue by sgmoore** [oleg-shilo/cs-script#122]
Is there something special you have to do to run csscript from a 64-bit host?
 
```var csScript = @"using System;
using System.Runtime.InteropServices;
using System.Data;

public class Test
{
	public Test()
	{
		Console.WriteLine(  Environment.Version + ""\r\n"" 
                                   + ((Marshal.SizeOf(typeof(IntPtr)) == 8) ? ""x64"" : ""x32""));
		DataSet ds = new DataSet(""Test"");
		Console.WriteLine(ds);
	}
}
";


 CSScriptLibrary.CSScript.Evaluator.ReferenceAssembliesFromCode(csScript) ;
 CSScriptLibrary.CSScript.LoadCode(csScript).CreateObject("*");
```
 

 

results in the error

 `
 // Could not load file or assembly 'file:///C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.`

This script works if the host is compiled for x86 and also works if I remove  ReferenceAssembliesFromCode line (but this is needed for other scripts).

Am I missing something?

PS. 
The absolute minimum code to show the error is 
` CSScriptLibrary.CSScript.Evaluator.ReferenceAssembliesFromCode("using System.Data;"); `

**Comment by oleg-shilo** [comment]
The problem is described here: https://github.com/oleg-shilo/cs-script/issues/9

You will need to adjust your code to avoid auto-referencing `System.Data` assembly and instead reference it manually. Or use an alternative compiling engine that is immune to the problem. 

Though I found your code sample is (most likely) captured inaccurately.  

```
CSScriptLibrary.CSScript.Evaluator.ReferenceAssembliesFromCode(csScript) ;
CSScriptLibrary.CSScript.LoadCode(csScript).CreateObject("*");
```

The code above does not make much sense. May be it is a typo. 
You need to use either "CSScript.Native" - calls like `CSScript.Load*()`.
Or "CSScript.Evaluator" - calls like `CSScript.Evaluator.Load*()`.

These two API models are completely isolated and do not affect each other. Thus `ReferenceAssembliesFromCode` coll has no affect on `CSScript.LoadCode` outcome.

https://github.com/oleg-shilo/cs-script/wiki/Choosing-Compiler-Engine
