### ISSUE TITLE
cs-script.core and <PrivateImplementationDetails>1 error

### ISSUE THREAD

**Issue by seertenedos** [oleg-shilo/cs-script#123]
Recently we started getting the error below with some of our scripts we are loading via CS-Script. Sadly this is not happening on simple scripts i can share and is only happening on larger ones that reference internal dll's etc.

we currently use the below method 

```C#
CSScriptLib.Eval.Roslyn.cs
public T LoadCode<T>(string scriptText, params object[] args) where T : class
{
    this.ReferenceAssemblyOf<T>();
    return (T)this.CompileCode(scriptText).CreateObject("*", args);
}
```

when we call this with some of our generated code we find Roslyn includes an extra class in the assembly called <PrivateImplementationDetails>1. It seems like the CreateObject(*,args) picks this class instead of our one resulting in the error "System.MissingMethodException: Constructor on type '<PrivateImplementationDetails>1' not found."

I would like to propose the following code as a fix for this issue.
```C#
public T LoadCode<T>(string scriptText, params object[] args) where T : class
{
    this.ReferenceAssemblyOf<T>();
    var assem = this.CompileCode(classAsString);
    var type = assem.ExportedTypes.FirstOrDefault(x => typeof(T).IsAssignableFrom(x));
    var instance = (T) assem.CreateObject(type.FullName, constructorArgs);
    return instance;
}
```

At the minute we are working around the issue in our application using the following but thought it would be better to integrate it into the library.

```
               var assem = CSScript.Evaluator
                    .ReferenceDomainAssemblies()
                    .CompileCode(classAsString);
                var type = assem.ExportedTypes.FirstOrDefault(x => typeof(TInstance).IsAssignableFrom(x));
                var instance = (TInstance) assem.CreateObject(type.FullName, constructorArgs);
```

which replaced

```
              TInstance instance = CSScript.Evaluator
                    .ReferenceDomainAssemblies()
                    .LoadCode<TInstance>(classAsString, constructorArgs);
```

**Comment by oleg-shilo** [comment]
Thank you for reporting it and sharing the work around.

Unfortunately Roslyn does a few undocumented things during the compilation. Thus one needs to unwrap the script actual class as Roslyn injects it into a parent "Submission" class along with a few other unwanted auto-classes:

![image](https://user-images.githubusercontent.com/16729806/45355713-6e36a700-b604-11e8-9da3-1aded035ba96.png)

Sadly, there is no reliable way of identifying user defined class automatically. This is the algorithm that CS-Script uses currently:

```C#
if (typeName == "*")
{
    //instantiate the first type found (but not auto-generated types)
    //Ignore Roslyn internal type: "Submission#N"; real script class will be Submission#0+Script
    foreach (Type type in asm.GetTypes())
    {
        bool isMonoInternalType = (type.FullName == "<InteractiveExpressionClass>");
        bool isRoslynInternalType = (type.FullName.StartsWith("Submission#") && !type.FullName.Contains("+"));

        if (!isMonoInternalType && !isRoslynInternalType)
        {
            return Activator.CreateInstance(type, args);
        }
    }
    return null;
}
else
...
``` 

While this algorithm works it may fail if Roslyn changes the compiling approach. And I am guessing this is what happens in your case.

The solution to the problem is to pass the type name (e.g. 'MyScript'):

```C#
TInstance instance = CSScript.Evaluator
                             .ReferenceDomainAssemblies()
                             .CompileCode(classAsString)
                             .CreateObject("MyScript", constructorArgs)
                             .Cast<TInstance>();
```
Though I do agree with your proposal. `IsAssignableFrom` is a great improvement for the wildcard type name.

Thank you, it will be incorporated in the next release.

**Comment by oleg-shilo** [comment]
Though the proposed solution will not help for the `public object LoadCode(string scriptText, params object[] args)` signature. 

Can you please share your test case so I can investigate it and possibly provide a stronger algorithm.
Or at least share the list of the types in the script assembly.

**Comment by seertenedos** [comment]
ok one suggestion for the method that does not take the type is change from asm.GetTypes() to asm.ExportedTypes.

Below is the types on my stuffed asm. Sorry can't share code but can give you want ever info you want off the asm.  Also you could create an interface that has nothing on it like IScript or something for all the classes you control. I did use the name to find the class at one stage as well but found the type match easier and better.

assem.GetTypes();
{System.Type[4]}
    [0]: {Name = "Submission#0" FullName = "Submission#0"}
    [1]: {Name = "<PrivateImplementationDetails>1" FullName = "<PrivateImplementationDetails>1"}
    [2]: {Name = "__Class" FullName = "Submission#0+__Class"}
    [3]: {Name = "<<Initialize>>d__0" FullName = "Submission#0+<<Initialize>>d__0"}
assem.ExportedTypes
{System.Type[3]}
    [0]: {Name = "Submission#0" FullName = "Submission#0"}
    [1]: {Name = "__Class" FullName = "Submission#0+__Class"}
    [2]: {Name = "<<Initialize>>d__0" FullName = "Submission#0+<<Initialize>>d__0"}

Also this does not happen for all scripts. we have about 100 simple scripts and they are all fine but have 20 big ones and most of them broke.

Lastly i did not realise the CreateObject was yours i thought it was from the Assembly class.  If you need to handle any class name you could use a simple pre-compiled regex to find the classname in the source and then find the type by name.  I did that as well before i moved to matching on type but i seem to have thrown that code away when i got type matching working.

**Comment by oleg-shilo** [comment]
Thank you.

> ...`ExportedTypes` vs. `GetTypes`...

I though about but decided to go with `GetTypes` as it lets instantiation of private types. This is particularly useful for the classless or method-only scripts.

So far it was no need to anything more sophisticated as it was no reports (until yours) about any Roslyn allocating type names outside of "Submission#0" naming convention.

 > ...use a simple pre-compiled regex to find the classname...

I could do even better with Roslyn CodeAnalysis. But the problem is that `CreateObject` has no access to the source code. It works with the assembly. `LoadCode` does, but it can do even better with your proposed `IsAssignableFrom` approach. This is what I am sticking to.

Thus the only case when `CreateObject` is going to be called with naked "*" is the case when user instantiates a type from a non-script assembly - no source code available. 

Anyway, I have used your `IsAssignableFrom` approach for and it will reliably cover the case of LoadCode. For all other cases the type auto-resolving algorithm cannot be warranted and user will need to pass the class name.

But I will update the resolving algorithm with handling the cases when the type name is a digit.

And I will consider using Roslyn to find the class name for the signatures where `<T>` is not available.
```C#
public object LoadCode(string scriptText, params object[] args)  
```

**Comment by oleg-shilo** [comment]
Done. The lates v1.0.2.0 NuGet package contains the solution that has the API you are interested in:

```C#
string asm = CSScript.Evaluator
                     .CompileAssemblyFromCode(
                                      @"using System;
                                        public class Script
                                        {
                                            public int Sum(int a, int b)
                                            {
                                                return a+b;
                                            }
                                        }", 
                                        "Test.dll");

```

**Comment by seertenedos** [comment]
i found one issue with the implementation i suggested when doing a new unit test which while is not an issue for me i thought i should mention it as may be for others. If you pass the type Object in for the script instance it will pick the wrong class and not find the constructor since every class inherits from Object.

Apart from that all our tests are passing with the new logic and that was the only thing i thought of that could and did break it. If they pass Object in you could potentially detect it and report it is not supported or run the old logic in that case that should work most of the time.

**Comment by oleg-shilo** [comment]
> If you pass the type Object in for the script...

What exact signature are you using? Can you share the code snippet?

**Comment by oleg-shilo** [comment]
That answers it. txs

**Comment by oleg-shilo** [comment]
The next release will have `CSScript.Evaluator.Check(string scriptText)` to cover this scenario.

**Comment by oleg-shilo** [comment]
Done.
Please use CS-Script.Core 1.0.3 package

**Comment by seertenedos** [comment]
Everything seems to be working correctly. I will let you know if i find anything further
