### ISSUE TITLE
Slow Execute on 1000 line script ...

### ISSUE THREAD

**Issue by iDirectSystem** [oleg-shilo/cs-script#125]
hi , When I load-code with Roslyn , it takes 14 second to compile it and run...

Can we reduce this time or remove it ? it's dynamic then why it takes time to compile ?

**Comment by oleg-shilo** [comment]
You post makes me smile. There is another soul that noticed that.

Roslyn is a beautiful but nasty beast. It is heave. I man really heavy. On my PC it takes about 5 seconds for it to initialize itself on first run. 

Being dynamic has nothing to do with it. Static MS C# compilers before Roslyn era showed in order of magnitude better startup performance than Roslyn. 

Roslyn team actually knows about that and tried a clever trick to improve the consecutive runs. Thus Roslyn compiler (csc.exe) is loaded via compiler service `VBCSCompiler.exe`, which keeps pre-loaded copy of the compiler all the time and talks to it via sockets. Thus the first run is still slow, but the next one is lightning fast.

Though this MS did not extend this trick for Roslyn Scripting namespace and it is also not available on Mono nor .NET Core.

I have no idea how you use CS-Script. You did not provide any details. But... 

- If you are using CS-Script as [standalone engine](https://github.com/oleg-shilo/cs-script/wiki/Standalone-Script-Execution) cscs.exe ensure you have enabled caching. This way CS-Script will never compile the script if it wasn't modified since the last run. Similar to Python caching.  
- If you are hosting CS-Script engine via [CSScript.Native](https://github.com/oleg-shilo/cs-script/wiki/Choosing-Compiler-Engine#csscriptnative) API you can benefit from the same caching mechanism. 
- If you are hosting CS-Script engine via [CSScript.Evaluator](https://github.com/oleg-shilo/cs-script/wiki/Choosing-Compiler-Engine#csscriptevaluator) then you cannot use caching as Roslyn scripting is incompatible with caching. Though you can call `RoslynEvaluator.LoadCompilers()` asynchronously at the application startup and it will save you some tome as Roslyn runtime will become partially loaded.
