### ISSUE TITLE
Persistent Caching Bug

### ISSUE THREAD

**Issue by joeynovak** [oleg-shilo/cs-script#13]
Hey Guys,

I may be totally missing something, but it seems to me that persistent caching is broken if using any of the LoadCodeFrom methods.  The first thing this method does is read all the code from the file and then save it to a temporary file whose name is based on a uuid.  

Is there a reason for this?

Thanks,

Joey

**Comment by oleg-shilo** [comment]
Hi Joey,

Originally there were only two loading APIs Load and LoadCode. First was a subject of source file based caching and the second one was compiling the code disassociated from any source file (with caching partially disabled). 

_Though the LoadCode needed to save the content into a temporary "throw away" file anyway as the MS compiler (CodeDOM code provider) required a **file** not an in-memory string. Since then CodeDOM improved but MSBuild, which was/is an engine for WPF scripts, still requires can work with files only._

Later on (Release v 3.6.0 (29/7/2013)) it was a feature request to extend the LoadCode with LoadCodeFrom. Why not to use just Load? Because some locations (e.g. network) were not convenient/compatible with the MS C# compiler, which requires file to be present locally. Another reason was that it would be the way to disable undesirable caching. _I do believe these two reasons are not valid any more._

Thus instead of doing this manually:
- Copy network file to a temp local file
- Compile temp local file with LoadFrom
- Delete local file

User could do it with just LoadCodeFrom. _To be honest I always thought that it is an overkill but the feature has been released anyway._

Though your post prompted me to review the code and update the XML documentation. Now it has some extra explanations and advice to use more straight forward Load method.

I wonder if it makes sense to mark it as obsolete and remove if no one complains. The whole CSScript.Load* API set became less relevant as CSScrpt.Evaluator.Load* currently is a recommended approach.

**Comment by joeynovak** [comment]
Hi Oleg,  

Thanks for the in-depth response.  Always a tough decision as to whether to change something or not after you have a large user base.  Personally, I would probably mark it as deprecated, and then in the xml docs tell people what to use instead (which you've done).  I've used a lot of libraries where deprecated code stayed around for a long time, sometimes even after a few major version releases.

For a User Story / some background.  I found it confusing because I wasn't even aware Load, and LoadFrom existed.  I was working on an inherited project (which did compile scripts from a network drive, but doesn't now), and was trying to find out why caching wasn't working.  And was naively assuming there wouldn't be two methods that did almost the exact same thing, but in a slightly different way.

Cheers!

Joey

**Comment by oleg-shilo** [comment]
>wasn't even aware Load, and LoadFrom existed.

This actually convinced me . I am marking it as deprecated. 

BTW have a look at CSScript.Evaluator.Loar* API set. It doesn't have this problem. It's extremely similar but more straight forward. And on top of it it offers the ability to switch between compiling engines: CodeDOM, Mono and Roslyn

Txs
