### ISSUE TITLE
csscript.CompilerException: (0,0): error CS0009: Metadata file

### ISSUE THREAD

**Issue by sohamakl** [oleg-shilo/cs-script#136]
I'm trying to use WinSCPnet.dll (https://winscp.net/eng/docs/library) as wrapper for winscp . The code it self is running very well from within visual studio but as cs-script I got in trouble and always receive an compiler error: 

"csscript.CompilerException: (0,0): error CS0009: Metadata file 'c:\...\WinSCP.exe' could not be opened -- 'An attempt was made to load a program with an incorrect format. '". 

Do you know a solution therefor?

**Comment by oleg-shilo** [comment]
The error itself is an indication that the host application (script engine in this case) and the assembly in question (WinSCPnet.dll) are compiled against different cpu type or the assembly is a native dll.

If it is the case then you will need either change the assembly or the script engine architecture:

cscs32.exe - x86
cscs.exe - CPU-neutral but will become x64 on x64 Windows

**Comment by oleg-shilo** [comment]
It's actually trickier.

The problem is caused by the WinSCP assembly file not being named appropriately (assembly name == file name). This leads to the attempt to load winSCP.exe instead of dll file. You can easily avoid this problem by preventing the the script engine to resolve the namespace `WinSCP` into the assembly. Though you will need to reference the correct assembly file explicitly. 

```C#
//css_ref WinSCPnet.dll
//css_ignore_namespace WinSCP
using System;
using WinSCP;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine(new SessionOptions());
    }
}
```

**Comment by sohamakl** [comment]
Excellent support, thank you very much.
