### ISSUE TITLE
Please update WSDL.exe and WSDL.cs to allow for TLS 1.2

### ISSUE THREAD

**Issue by UweKeim** [oleg-shilo/cs-script#138]
I've built a patch to allow the WSDL.CS to work with servers that only support TLS 1.2.

Basically I'm replacing the WSDL.EXE with a newer one and add some code to WSDL.CS.

**My request is:**

- Could you please update WSDL.CS to something similar than in [my patch](https://gist.github.com/UweKeim/59bb3ab47575166716d32a409d96ca77)?
- Could you please update WSDL.EXE to something similar than in [my patch](https://www.dropbox.com/sh/azzggtkzp4mxto4/AAA_hmSIto6pDLhVnMaoUKO8a?dl=0)?

(I've disassembled WSDL.EXE, made a SLN and adjusted some code, then compiled it again).

**Comment by oleg-shilo** [comment]
Hi Uwe,

Not a problem. There is no problem at all with updating the _wsdl.cs_. Though adding executables is a challenge. I have already been asked by the suspicious users about the origin of some other third-party executables in the CS-Script distro (e.g. resgen.exe, nuget.exe and tlbimpl.exe). 

It was easy to answer as the executables were official builds of the products licenced and maintained by other vendors. But in this case it will be difficult to answer the same question since _wsdl.exe_ was decompiled and rebuilt. And I am not even talking the copyrights implications, that CS-Script distro most likely will be breaking.

The best way would be to find and modify the open source equivalent of _wsdl.exe_. Or already working proprietary equivalent that is liberally licensed.

Let me know if you know product like that and I will happily include it in the distro.

**Comment by UweKeim** [comment]
Thanks, Oleg! Even modifying WSDL.CS would help my patching, since I only have to replace the WSDL.EXE and not need to modify the WSDL.CS anymore.

**Comment by oleg-shilo** [comment]
Not a problem. Done. Will be available in the next release.

**Comment by UweKeim** [comment]
Awesome!

**Comment by oleg-shilo** [comment]
Yeah, go for it. If it fits the purpose Ils just do the copyright acknowledgement and add the product to the distro. Should you decide to modify it, not a problem. MIT allows that.

**Comment by oleg-shilo** [comment]
bummer...

**Comment by jonathancounihan** [comment]
> I've built a patch to allow the WSDL.CS to work with servers that only support TLS 1.2.
> 
> Basically I'm replacing the WSDL.EXE with a newer one and add some code to WSDL.CS.
> 
> **My request is:**
> 
> * Could you please update WSDL.CS to something similar than in [my patch](https://gist.github.com/UweKeim/59bb3ab47575166716d32a409d96ca77)?
> * Could you please update WSDL.EXE to something similar than in [my patch](https://www.dropbox.com/sh/azzggtkzp4mxto4/AAA_hmSIto6pDLhVnMaoUKO8a?dl=0)?
> 
> (I've disassembled WSDL.EXE, made a SLN and adjusted some code, then compiled it again).

@UweKeim please can you share the WDSL.exe you have updated or a solution to connect to TLS 1.2 server only? I am facing the same issue :( I cannot make the WSDL exe generate from an endpoint.

**Comment by UweKeim** [comment]
Here is the file: [wsdl.zip](https://github.com/oleg-shilo/cs-script/files/8533867/wsdl.zip)

Please use at your own risks.

**Comment by oleg-shilo** [comment]
Thank you Uwe.
Glad you are able to cover this one :)

**Comment by jonathancounihan** [comment]
Thanks for the help @UweKeim , @oleg-shilo. no luck I still have the same issue. I suspect the server hosting the WSDL has not got the correct cipher suites installed or there is some other issue.

**Comment by oleg-shilo** [comment]
Jonathan, at the end of the day cs-script is only automating wsdl generation via invoking the included wsdl.exe through the wsdl.cs script.

If your Web Service interface is stable you can run any version of wsdl.exe manually, generate a service proxy file and after that simply reference it from your script. If automation does not work... do it manually :)
