### ISSUE TITLE
.NET Standard 2.0 / .NET 4.6.1

### ISSUE THREAD

**Issue by nilslahr** [oleg-shilo/cs-script#151]
I'm a bit confused between the releases and source code build options.

1. Extracting the .NET-Core CSScriptLib and cs-script, it seems to allow .NET Core 1.3.  We target .NET Standard 2.0 which I thought could the be used by .NET Core 2.0.  

2. The source code builds using the "Source\Build\build.cmd" but this does not seem to build CSScriptLibrary-v4.5, nor the CSSRoslynProvider.  Additionally the build directory shows the various EXE files that were built, but no "\Source\Build\lib\" so when I run "css_config.exe" it show an error saying it can't find the 'lib' directory.  

My goal is to compile either 4.6.1 or .NET Core 2.0 code with NuGet packages included.  I have an older version of CS-Script that I use for this, including some small modifications, but I was hoping to get the latest code and build against the newer targets.

Short story.  I'm confused.  Building by hand doesn't seem to create the proper files to run, like the release zips, while I'm unsure if the .NET-Core release 7z zips actually contain what I need to include my .NET Standard 2.0 NuGet Package.  I would like to build the code, just in case I need modifications.

Any help would be much appreciated.
Regards,
Nils

**Comment by oleg-shilo** [comment]
> My goal is to compile either 4.6.1 or .NET Core 2.0 code with NuGet packages included.

As you have probably noticed CS-Script has two repositories now:
.NET Full: https://github.com/oleg-shilo/cs-script
.NET Core: https://github.com/oleg-shilo/cs-script.core

It is a reflection of the fact that .NET Core is on the raise and it will imminently replace .NET Full as a trully portable distro. 

The reason for a separate distro CS-Script could not be compiled for .NET Core without conceptual changes addressing some .NET Core limitations. It is also an opportunity to remove from CS-SCript features that did not get any significant traction with the users.

CS-Script is being gradually phased out and CS-Script.Core will eventually become the primary distro.

CS-Script for .NET Full is relying on MSBuild (build.cmd) for building the distrio. And Visual Studio for building debuggable executables.

CS-Script for .NET Core is relying completely on VIsual Studio (dotnet.exe) for building the distrio. 

Both distros are intended to be used for deploying CS-Script via Chocolaty. And the class library for hosting in the applications is deployed via NuGet packages. `cs-script` and `cs-script.core` correspondingly. 

Since your host application is .NET Core, I suggest that you use `cs-script.core` NuGet package. It should solve your problem:

![image](https://user-images.githubusercontent.com/16729806/54613439-cfa56a00-4aae-11e9-91cd-e2195e1dd139.png)

![image](https://user-images.githubusercontent.com/16729806/54613476-e055e000-4aae-11e9-9924-d72d944d5488.png)
 
![image](https://user-images.githubusercontent.com/16729806/54614253-35462600-4ab0-11e9-91e9-4a05f5ed6d67.png)
