### ISSUE TITLE
IsOutOfDateAlgorithm  Always return true

### ISSUE THREAD

**Issue by NicolasVautrin** [oleg-shilo/cs-script#168]
Hello,
           
IsOutOfDateAlgorithm  Always return true , do you know why ?

CSScript.CacheEnabled = true;

            CSScript.IsOutOfDateAlgorithm = (script, dll) =>
            {
                bool ret = CSScript.CachProbing.Advanced(script, dll);
                return ret;
            };
               var code = @"int Sqr(int a)
                            {
                                return a * a;
                            }";

                dynamic script = CSScript.LoadMethod(code, "sqrt.dll", true).CreateObject("*");

**Comment by NicolasVautrin** [comment]
I set this option :
CSScript.GlobalSettings.LegacyTimestampCaching = false;

this is MetaDataItems bettween 2 Runs

[Run 1]
stampID : -1489757098
version : -285949787
compileOptions : 0
debug : 1
count : 764
False 06/07/2019 07:43:35 E:\SRC_AG2L_COMMUN\Nicolasv\Industria\Root\TestMono\bin\Debug\dynamic\85804.0559df41-b21c-45bc-bfe8-1c1e2b2b84b2.tmp
True 07/03/2017 09:55:44 Microsoft.CodeAnalysis.CSharp.dll
True 06/07/2019 07:41:55 TestMono.exe
True 05/11/2016 03:56:08 System.IO.FileSystem.dll
True 17/04/2019 12:29:14 CSScriptLibrary.dll
True 19/12/2016 11:20:32 System.Reflection.Metadata.dll
True 07/03/2017 09:55:52 Microsoft.CodeAnalysis.Scripting.dll
True 07/03/2017 09:55:40 Microsoft.CodeAnalysis.dll
True 19/12/2016 11:17:42 System.Collections.Immutable.dll
True 05/11/2016 03:57:14 System.Security.Cryptography.Algorithms.dll
True 05/11/2016 03:57:30 System.ValueTuple.dll
True 05/11/2016 03:57:18 System.Security.Cryptography.Primitives.dll
True 07/03/2017 09:55:46 Microsoft.CodeAnalysis.CSharp.Scripting.dll
[Run 2]
stampID : -1489757098
version : -285949787
compileOptions : 0
debug : 1
count : 764
False 06/07/2019 07:43:35 E:\SRC_AG2L_COMMUN\Nicolasv\Industria\Root\TestMono\bin\Debug\dynamic\85804.0559df41-b21c-45bc-bfe8-1c1e2b2b84b2.tmp
True 07/03/2017 09:55:44 Microsoft.CodeAnalysis.CSharp.dll
True 06/07/2019 07:41:55 TestMono.exe
True 05/11/2016 03:56:08 System.IO.FileSystem.dll
True 17/04/2019 12:29:14 CSScriptLibrary.dll
True 19/12/2016 11:20:32 System.Reflection.Metadata.dll
True 07/03/2017 09:55:52 Microsoft.CodeAnalysis.Scripting.dll
True 07/03/2017 09:55:40 Microsoft.CodeAnalysis.dll
True 19/12/2016 11:17:42 System.Collections.Immutable.dll
True 05/11/2016 03:57:14 System.Security.Cryptography.Algorithms.dll
True 05/11/2016 03:57:30 System.ValueTuple.dll
True 05/11/2016 03:57:18 System.Security.Cryptography.Primitives.dll
True 07/03/2017 09:55:46 Microsoft.CodeAnalysis.CSharp.Scripting.dll

**Comment by NicolasVautrin** [comment]
Ok , tmp file of the first Run no more exist at 2nd Run.
Is there any cleanup i miss between two Run ?

**Comment by NicolasVautrin** [comment]
well i've miss this step 
ScheduleCleanup();
existant dll will never be in sync if tmp files no more exists ...

**Comment by oleg-shilo** [comment]
An important point is that `IsOutOfDateAlgorithm ` is an algorithm that answers the question "Is the script file changed since the last execution?"

Since you are not using **script file** but **script code**, the algorithm will always respond "yes the script file is changed". This response is the only reliable logical return result as script code is written in a random script file before being executed. Thus every time it is a new file.

Saying that `CSScript.CacheEnabled = true` still works within a single session (process). Thus if you call ` CSScript.LoadMethod(code, "sqrt.dll", true) ` N times it will be compiled only once. Thus a break point in your ` CSScript.IsOutOfDateAlgorithm = (script, dll) => . . .` will be fired only once.

If you truly need to achieve inter-session caching then you will need to handle `code->wrap to class->file` transition by yourself. 

CS-Script can help with wrapping but quite possibly the per-session caching will be just enough. Your call...

**Comment by NicolasVautrin** [comment]
Ok I understand.
Thanks
