### ISSUE TITLE
Can it modify to run on iOS with embed mono

### ISSUE THREAD

**Issue by srxqds** [oleg-shilo/cs-script#179]
Can it modify to run on iOS with embed mono?

**Comment by oleg-shilo** [comment]
I am not sure if "embedded mono" is a special distro of mono but yes CS-Script can run on Mono.

See https://github.com/oleg-shilo/cs-script/wiki/CS-Script-on-Linux

When CS-Script for Mono was developed it was successfully tested on both iOS and Linux but I haven't tested the latest release(s) on iOS since I don't have it available for testing.

**Comment by srxqds** [comment]
ok, thank you.
I found the **Mono.CSharp** can meet my need!

**Comment by oleg-shilo** [comment]
I am not sure I follow.

`Mono.CSharp` is not an app but a class library assembly. Thus it can only run by the hos application. If it is the scenario you are looking for then CS-Script assembly (NuGet package) can be used out of box on Mono and it will actually run `Mono.CSharp` under the hood.

Though if you are looking for the latest C# syntax then you will need to switch to CS-Script for .Net.Core as `Mono.CSharp` does not support it.

However if you are looking for a stand-alone engine app, in the absence of the context I assumed it is the case, then you need to use CS-Script  executable (cscs.exe).  The latest releases have been tested on Mono for Win and Linux but not on iOS.

The stand-alone engine app is also available for .NET.Core on all OSs.
