### ISSUE TITLE
Load compiled assembly in CS-Script

### ISSUE THREAD

**Issue by mrn-aglic** [oleg-shilo/cs-script#185]
I was wondering if it is possible to load a class using CS-Script Core and reference it when executing another CS-Script or reference it from Roslyn? 

E.g.

```
var code2 = @"
using System;
using System.Collections.Generic;
using System.Linq;

public class Usings
{
    static void Main(string[] args)
    {
        var x = new List<int> {1, 2, 3, 4, 5};
        var y = Enumerable.Range(0, 5);
        
        x.ForEach(Console.WriteLine);
        var z = y.First();
        Console.WriteLine(z);
    }
}";
var state = CSScript.Evaluator.ReferenceAssembliesFromCode(code2);
state.CompileCode("var x = new Usings();");
```

I get the error 

> The type or namespace name 'Usings' could not be found

**Comment by oleg-shilo** [comment]
Well, there area a few interesting issues with your code. Mostly caused by the Roslyn limitations but not your mistakes. Still let's fix a few of them first:

- `CompileCode("var x = new Usings();` is invalid in this context. The code you supplied is not a C# complaint class definition as required:
![image](https://user-images.githubusercontent.com/16729806/71636904-9b8ce580-2c8b-11ea-8c62-87c50741f329.png)
Your `code2` is what you need to compile with `CompileCode`

- Your call `ReferenceAssembliesFromCode` does not do what you want it to do (compile and reference the script). It finds what are the assemblies you want to reference in the supplied code:
![image](https://user-images.githubusercontent.com/16729806/71636922-f32b5100-2c8b-11ea-8ef5-f6f737dd0991.png)<br>Definitelly not what you want.

========================

Now the problem you are experiencing with the CS-Script version you are using is caused by the fundamental hosting limitations Roslyn has. The most critical one is the inability to have a class in your script that can be referenced by other scripts due to the fact that Roslyn always decorates your class with the parent root-class that has illegal characters in the name ( `Submission#0`), meaning it cannot be used in any C# code. Full stop. 

And even the work around that Roslyn "provided" (custom root-class name) did not work  (tested  17 Jul 2019). 

Fortunately... after your post I retested the work around, which was integrated in CS-Script.Core all along and to my joy I found that now it works. Meaning that I only need to enable the work around and to do a new release. 

I have done this now. You can find the latest package (v1.2.3) that supports running one script from another one. NuGet: https://www.nuget.org/packages/CS-Script.Core

Though I am still writing the Wiki that describes how to use this new feature: https://github.com/oleg-shilo/cs-script.core/wiki/Advanced-hosting-scenarios.

 You can either wait a few days until I finish the wiki or you can try to use the release and figure it out by yourself. 

Hint. It will be something similar to my test code:
```C#
public void Issue_185()
{
    // CSScript.EvaluatorConfig.DebugBuild = true;

    var code2 = @"
using System;
using System.Collections.Generic;
using System.Linq;

public class Usings
{
    static void Main(string[] args)
    {
        var x = new List<int> {1, 2, 3, 4, 5};
        var y = Enumerable.Range(0, 5);

        x.ForEach(Console.WriteLine);
        var z = y.First();
        Console.WriteLine(z);
    }
}";

    var info = new CompileInfo { RootClass = "code2" };
    CSScript.RoslynEvaluator.CompileCode(code2, info);

    dynamic script = CSScript.Evaluator
                                .ReferenceAssembly(info.AssemblyFile)
                                .CompileMethod(@"using static code2;
                                    Usings Test()
                                    {
                                        return new Usings();
                                    }")
                                .CreateObject("*");
    script.Test();
}
```

**Comment by mrn-aglic** [comment]
I've tried your test code, it works for me nicely! Thank you very much. 👍 
I'll still have to dig a little deeper to see if there are any other limitations.
