### ISSUE TITLE
Running cs-script in mixed winforms and wpf project

### ISSUE THREAD

**Issue by mrockwell** [oleg-shilo/cs-script#199]
I was able to successfully implement cs-script inside a cs-script wpf project. however, when i tried to port the code into my main project which is a mix of both winforms and wpf (winforms is primary) i get an error. here's code snippiet:

```C#
                try
                {
                    Assembly script = CSScriptLibrary.CSScript.Evaluator
                                            .ReferenceAssemblyOf<DataSet>()
                                            .With(eval => eval.DisableReferencingFromCode = true)
                                            .CompileCode(scriptCode);

                    errorMessage = SuccessfullyCompiled;
                    return true;
                }
                catch (Exception ex)
                {
                    errorMessage = ex.Message;
                }
```
The exception text:
```
"Could not load file or assembly 'file:///C:\\Windows\\system32\\WinMetadata\\Windows.UI.winmd' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)":"file:///C:\\Windows\\system32\\WinMetadata\\Windows.UI.winmd"
```

I have no idea why it's trying to load windows.ui.winmd. I do notice in my standalone app the following are successfully loaded:
Windows.Graphics.winmd, Windows.Perception.winmd, Windows.ApplicationModel.winmd, Windows.Web.winmd and several more but, difference is, standalone wpf version never attempts to load windows.ui.winmd like it does with my main app. Any help would be appreciated. Thanks.

**Comment by oleg-shilo** [comment]
Most likely it happens because the engine is trying to reference (when compiling the script) the assemblies currently loaded in the executing `AppDomain`. 

Normally it is exactly what you want but in case of complicated assembly loading and probing scenarios (e.g. mixed runtime hosting like yours) things can get messy.

So try to disable referencing the domain assemblies and reference explicitly only required assemblies (like you did with `DataSet`).:

```C#
CSScript.EvaluatorConfig.RefernceDomainAsemblies =  false;
```
If this does not help create and share a simple hello world project  that demosnstrates the problem and I will have a look.

**Comment by mrockwell** [comment]
your recommendation to turn off referncedomainassemblies worked. thanks for the help.
