### ISSUE TITLE
[Bug] precompiler/context["CompilerOptions"] doesn't appear to work

### ISSUE THREAD

**Issue by rconde01** [oleg-shilo/cs-script#203]
cs-script 3.28.9.0

test.cs
```
//css_precompiler precompiler.cs;

unsafe class A{}
```

precompiler.cs
```
using System;
using System.Collections;

class Precompiler
{
   public static bool Compile(ref string content, string scriptFile, bool IsPrimaryScript, Hashtable context)
   {
      context["CompilerOptions"] = context["CompilerOptions"] + " /unsafe";

      return false;
   }
}
```

result:
```
cscs test.cs
Error: Specified file could not be compiled.

csscript.CompilerException: C:\Users\Me\Desktop\cs_script_unsafe\test.cs(3,14): error CS0227: Unsafe code may only appear if compiling with /unsafe

   at csscript.CSExecutor.ProcessCompilingResult(CompilerResults results, CompilerParameters compilerParams, ScriptParser parser, String scriptFileName, String assemblyFileName, String[] additionalDependencies)
   at csscript.CSExecutor.Compile(String scriptFileName)
   at csscript.CSExecutor.ExecuteImpl()
```

**Comment by oleg-shilo** [comment]
The observed behavior is caused by the fact that you are modifying the context member that is not expected to be be modified so the modified value is never pushed back to the compiler.

The expected use of the `context` argument is:
- all values with the key that starts with "new" are to store user injected new execution context. (e.g. `context["NewSearchDirs"]`, `context["NewIncludes"]`)
- all values with the key that does not start with "new" are to allow user to read execution context (e.g. `context["SearchDirs"]`, `context["CompilerOptions"]`). 

Thus `context["CompilerOptions"] = context["CompilerOptions"] + " /unsafe";` is expected to make no difference.

However I think it is a useful feature to allow user to inject compiler options. So I have added a new key/value pair `context["NewCompilerOptions"]`. Thus your precompiler should use it like this:

```C#
context["NewCompilerOptions"] = "/unsafe";
```

The fix is done and will be available in the very next release.

**Comment by rconde01** [comment]
Great! I would update the documentation too (unless I missed it somewhere).

**Comment by oleg-shilo** [comment]
> documentation 
yes of course

And... need to implement it in cs-script.core as well. 😄 
Cannot wait til .NET5 is out so I can stop maintain two parallel repositories.
