### ISSUE TITLE
AppHosting doesn't seem to support //css_autoclass

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#209]
Error message:
`Script.cs(7,1): error CS0116: A namespace cannot directly contain members such as fields or methods`

Is this intentionally disabled for AppHosting? Or does `CSScript.CompileWithConfig()` need to be called with special settings?

**Comment by oleg-shilo** [comment]
Evaluators are following a hosting different paradigm. The are not expected to execute scripts but rather compile and load load classes, methods and delegates. Thus some of the directives like `//css_autoclass` are not compatible with these scenarios.

It is described here: https://github.com/oleg-shilo/cs-script/wiki/Choosing-Compiler-Engine#csscriptevaluator

If you reference CS-Script nuget package it comes with the samples for all supported scenarios. 

There are quite a few examples of scripts without the class definition (e.g. LoadDelegate). Kind of the scenario where you would use `//css_autoclass` wit cscs.exe: 

```C#
var product = CSScript.Evaluator
                      .LoadDelegate<Func<int, int, int>>(
                                  @"int Product(int a, int b)
                                    {
                                        return a * b;
                                    }");

int result = product(3, 2);
```

**Comment by maettu-this** [comment]
Hmm, I am not fully getting the jump from `CSScript.CompileWithConfig()` to `CSScript.Evaluator.LoadDelegate()`, but I guess it has the same root cause we ran into in the past: My hosting app allows the users to write their own scripts. So, if the user sees the `//css_autoclass` feature on the CS-Script website and wants to use it, my app will still `CSScript.CompileWithConfig()` and so on.

I guess I will have to tell my users that this feature of CS-Script is not supported by my app. I think this is an acceptable limitation.

**Comment by oleg-shilo** [comment]
Hosted CS-Script has two hosting models _CS-Script.Native_ (your case) and _CS-Script.Evaluator._ 
Read more here https://github.com/oleg-shilo/cs-script/wiki/Choosing-Compiler-Engine#csscriptnative

For quite some time CS-Script.Evaluator became a direction of the CS-Script evolution. I still maintained both models for compatibility reasons. But since .NET is moving .NET-Core native version of CS-Script will no longer be available anyway. And it does not support C# syntax higher than C#5 unless the compilation tunneled to Roslyn, which is the base of the  CS-Script.Evaluator anyway.

Thus I say your users will have to migrate. Encourage them bye the goodnesses of C#9 

And _autoclass_ is supported in C#9 natively. With the delay ~10 years after CS-Script released it first time MS finally introduced the same feature under the name "_top-class_" 😄 
Sorry for shamelessly bragging.

But on a serious note, you need to start planing for your product to migrate to .NET 5 (aka .NET Core)
