### ISSUE TITLE
ASP Core with net461 framework got System.IO.FileLoadException

### ISSUE THREAD

**Issue by nike61** [oleg-shilo/cs-script#21]
When I try to add nuget package to ASP Core project with full .NET I receive exception:

```
An exception of type 'System.IO.FileLoadException' occurred in Microsoft.AspNetCore.Mvc.Razor.dll but was not handled in user code

Additional information: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

My configuration:
```
"frameworks": {
    "net461": {
      "dependencies": {
        "Visiology.VA.DAL": {
          "target": "project"
        },
        "Visiology.VA.DAL.CsDataService.Shared": {
          "target": "project"
        },
        "Visiology.VA.DAL.Interfaces": {
          "target": "project"
        }
      }
    }
  }
```

Dependencies:
```
"dependencies": {
    "Autofac.Extensions.DependencyInjection": "4.0.0",
    "CS-Script.bin": "3.18.1",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "MongoDB.Driver": "2.3.0",
    "Serilog.Extensions.Logging": "1.3.1",
    "Seterlund.CodeGuard": "2.3.4",
    "SSH.NET": "2016.0.0"
  }
```

**Comment by oleg-shilo** [comment]
I don't have .NET Core handy so I cannot test. But this is what you can do to resolve the problem. 

The NuGet CS-Script.bin package content is grouped by CLR version.  And placed in the individual folders of the CLR TargetVersion of your VS project. Tough I am not sure how .NET Core VSCode does it. 

The problem is most likely caused by the assemblies being referenced from the package folder that does not contain Microsoft.CodeAnalysis.CSharp.dll (e.g. `packages\CS-Script.bin.3.18.1.0\lib\net45`). 

If you ensure that you reference assemblies from the folder with the full set of dependencies (e.g. `packages\CS-Script.bin.3.18.1.0\lib\net46`) then most likely the problem will go away.

Alternatively you may completely avoid `Microsoft.CodeAnalysis` dependency if you do not use Roslyn at all. See if setting the engine to Mono or CodeDom get you through:
```C#
CSScript.EvaluatorConfig.Engine = EvaluatorEngine.Mono;
//or 
CSScript.EvaluatorConfig.Engine = EvaluatorEngine.CodeDom;
```
Let me know if it hepled.

**Comment by nike61** [comment]
It seems that ASP Core needs Microsoft.CodeAnalysis.CSharp version >= 1.3.0. But cs-script uses 1.2.0 version. I can't downgrade ASP Core to use 1.2.0 because I'm getting following error:
```
Microsoft.AspNetCore.Mvc (>= 1.0.0) -> Microsoft.AspNetCore.Mvc.Razor (>= 1.0.0) -> Microsoft.CodeAnalysis.CSharp (>= 1.3.0)
Microsoft.CodeAnalysis.CSharp.Scripting (>= 1.2.0) -> Microsoft.CodeAnalysis.CSharp (= 1.2.0).
```

That also didn't helped:
`CSScript.EvaluatorConfig.Engine = EvaluatorEngine.CodeDom;`

Can I somehow make cs-script use 1.3.0 version?

Thank you for help!

**Comment by oleg-shilo** [comment]
OK, I think there is some misunderstanding here. CS-Script is not build for Roslyn 1.2 It will use whatever Roslyn is available at runtime. Thus recompiling it will not change anything.

I asked you to set the engine to `CodeDom` because I wanted CS-Script not to use Roslyn at all and load `ICodeCompiler` instead. `ICodeCompiler` is normally a part of any .NET runtime. I cannot understand from your short description what is the problem but I do trust you it didn't work. Most likely because .NET Core doesn't implement this interface.

I also asked you to try to set the engine to `Mono` because I wanted CS-Script not to use Roslyn and load `Mono.CSharp.Evaluator` instead. `Mono.CSharp.Evaluator` is a single no dependency assembly , which is distributed with CS-Script. Though I have no feedback on that yet.

If you really want to (or have to) use Roslyn you can just bring a single CSScriptLibrary.dll into your project and use it with any compatible version of Roslyn. Roslyn v1.3.2 seems OK.
Just to make it simpler and not to deal with many conflicting Roslyn binaries from various packages I have created a single "raw" NuGet package `CS-Script.lib`, which only delivers CS-Script and no other dependencies. 

I have described this very same topic here: https://github.com/oleg-shilo/cs-script/wiki/Using-custom-version-of-Roslyn. It describes what exact Roslin assemblies you will need. The techniques was tested with CS-Script v3.18.1.0 and Roslyn v1.3.2 in a Console application project. 

The fact that you your environment does not complain about CSScriptLibrary.dll means that the assembly is most likely compatible with .NET Core runtime and solving the problem is only a matter of removing unwanted Roslin binaries and replacing them with the correct ones.

**Comment by nike61** [comment]
The CS-Script.lib saved my life. Thank you!

**Comment by oleg-shilo** [comment]
>The CS-Script.lib saved my life. Thank you!

Don't forget to name your firstborn "Oleg" :) :)

And on a serious note. Can I consider your feedback as a confirmation that that ASP.NET as an environment is compatible with CS-Script infrastructure?

**Comment by nike61** [comment]
:) Yes it works, but I use Asp Core with .NET Full Framework, not .NET Core. So I use the following configuration in ASP Core:
```
"frameworks": {
    "net461": {
    }
}
```

**Comment by oleg-shilo** [comment]
Great. Thank you. 
I'll need to find time to test it against .NET Core

**Comment by matthiasburger** [comment]
great library for .net framework. i wanted to use it together with my web-application on .net core. 
do you have any results so far? else, I'm going to test it for you on .net core this evening and send you some feedback. + if it succeeds I'm going to test it with my web-application, using entity framework and all that stuff.

**Comment by oleg-shilo** [comment]
Please see my extended test report in this therad https://github.com/oleg-shilo/cs-script/issues/18
