### ISSUE TITLE
Error message uses a non-Windows \n instead of e.g. Environment.NewLine

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#213]
The error message shown in https://github.com/oleg-shilo/cs-script/issues/25#issuecomment-714497110 erroneously states `"Cannot parse \"//css_reference\nEnsure your directive escapes all delimiters (';(){},') by doubling the delimiter character."` even though I am running on Windows. Thus splitting the string for `Environment.NewLine` will not work. I propose to always use `Environment.NewLine` when composing multi-line strings.

(Moved from #25 to new issue here.)

**Comment by oleg-shilo** [comment]
Well it's a tricky one. 
The good practice dictates that you should not expect exact line ending type even if you know the OS you are running on. Thus your splitting routine should handle both `\r\n` and `\n`.

This is what I usually use:
```C#
    public static string[] GetLines(this string str) =>// too simplistic though adequate
        str.Replace("\r\n", "\n").Split('\n');
```
And of course the production strength algorithm should be based on more comprehensive RegEx.

Thus I have the tendency to deal with the string Linux way. Particularly because majority of all Windows utils handle `\r\n` and `\n` transparently (cmd, powershell, notepad++).

Nevertheless, I do not close this issue and will normalize output strings in the next release.
