### ISSUE TITLE
String interpolation doesn't work

### ISSUE THREAD

**Issue by gmgunderground** [oleg-shilo/cs-script#218]
Look the following image, If I use string interpolation when I run the application I get error "character "$" unpredictable "
Without string interpolation all it is working fine. I'm using C# Console application with Framework .NET 4.7.2

Regards
GMG

![Immagine 2020-12-05 213214](https://user-images.githubusercontent.com/3244031/101262816-87762180-3741-11eb-9b7b-d789ed0ddc14.png)

**Comment by oleg-shilo** [comment]
Since CS-Script relies .NET for script compilation the supported C# syntax by default is limited to C# 5 as MS has stopped shipping C# compilers after version C# 5.

However you can enable support for the latest version of C# by integrating C# compilers NuGet package provided by MS into  your application. 

Read more here: https://github.com/oleg-shilo/cs-script/wiki/C%23-latest-syntax-support-(hosted)

**Comment by gmgunderground** [comment]
Thank you so much for the clarification
