### ISSUE TITLE
DirectoryNotFoundException in install.cmd "...\cs-script\Lib\Bin\Roslyn"

### ISSUE THREAD

**Issue by fredlllll** [oleg-shilo/cs-script#223]
hi, me again

just downloaded the v3.30.5.1 release, unpacked it and ran install.cmd on a somewhat fresh windows 10 install. it seems to have finished installing as cscs.exe is callable from console.

screenshot of the german error message https://i.imgur.com/ksLTUbS.png

this is similar to another issue i opened a long time ago, but now its a different folder. sorry for not answering on that one, kind of forgot about it

**Comment by oleg-shilo** [comment]
Hi Frederik,

Sorry, the problem you are experiencing is the result of a packaging mistake during the build of the release distro. 
It is crazy time now and I regret that I did the release in such a hurry. The result is that the distro is packaged incorrectly and your problem is the second one reported. In your case the distro does not contain `root\lib\bin\Roslyn`

I have re-released the same build but with incremented version to reflect packaging fix: https://github.com/oleg-shilo/cs-script/releases/tag/v3.30.5.2

Just in case, I have marked it as pre-release so please let me know if it addressed your problem and I will drop the `pre-` prefix

**Comment by fredlllll** [comment]
yes this has solved it :D

**Comment by oleg-shilo** [comment]
Fantastic. Thank you.
Merry Christmas :)
