### ISSUE TITLE
Information about referencing DLLs is hard to find

### ISSUE THREAD

**Issue by qwertie** [oleg-shilo/cs-script#225]
When I arrived at the cs-script home page I first clicked "CS-Script.Core". There wasn't much documentation there, so next I clicked "Documentation Wiki".

The wiki is not searchable, so I looked in the local page for "reference" - not found. FAQ - not found. "question" - I am told I should be looking in this very wiki for answers to my questions!

Next I see a link to "online documentation" - 404 not found.

Next I click "Top level documentation" and search for "reference" - once again I am told to look in "the online documentation." - 404 not found.

Then I see a link to "Additional documentation" - takes me back to the wiki.

Hmm. So how do I reference DLLs?

- System DLLs?
- User-defined DLLs?
- NuGet packages?

<hr/>

Also, I came here because I built my own C# tooling infrastructure which I think could make cs-script more powerful. It's a tool called LeMP, built on a superset of C# called Enhanced C#. It allows you to do arbitrary transformations on your C# code before running it using "macros". For example, here's a macro I'm fond of:

~~~cs
define change_temporarily($lhs = $rhs)
{
  var temp# = $lhs; // save old value in uniquely-named variable
  $lhs = $rhs;
  on_finally { $lhs = temp#; }
};

// Changes the current directory and runs "dir"
// Current directory changes back automatically at the end!
void CallDir(string folder)
{
  change_temporarily(Environment.CurrentDirectory = folder);

  Process p = new Process();
  p.StartInfo.FileName = "dir";
  p.StartInfo.UseShellExecute = false;
  p.StartInfo.RedirectStandardOutput = true;
  p.OutputDataReceived += (sender, args) => Console.WriteLine("received output: {0}", args.Data);
  p.Start();
  Console.WriteLine(p.StandardOutput.ReadToEnd());
}
CallDir(@"C:\Dev");
~~~

LeMP converts this to ordinary C#:

~~~cs
// Changes the current directory and runs "dir".
// Current directory changes back automatically at the end!
void CallDir(string folder)
{
	var temp10 = Environment.CurrentDirectory;	// save old value in uniquely-named variable
	Environment.CurrentDirectory = folder;
	try {

		Process p = new Process();
		p.StartInfo.FileName = "dir";
		p.StartInfo.UseShellExecute = false;
		p.StartInfo.RedirectStandardOutput = true;
		p.OutputDataReceived += (sender, args) => Console.WriteLine("received output: {0}", args.Data);
		p.Start();
		Console.WriteLine(p.StandardOutput.ReadToEnd());
	} finally { Environment.CurrentDirectory = temp10; }
}
CallDir(@"C:\Dev");
~~~

It would be cool if `css code.ecs` could see the ecs extension and run the script via LeMP. What do you think?

**Comment by oleg-shilo** [comment]
The CS-Script.Core repository is for .NET Core specific implementation and all that little documentation you may find there is specifically covering .NET Core inflicted scenarios.   
For a default features like assembly referencing the advice is to access this information on the main repo CS-Script.
![image](https://user-images.githubusercontent.com/16729806/104602451-871d5e80-56cf-11eb-8066-3da6d2a97796.png)

BTW with the arrival of .NET 5 all CS-Script.Core content is to be moved/merged to th CS-Script GitHub repo.

>The wiki is not searchable, 

On GitHub wiki is searchible via Github infrastructure. But of course since your topic is general you will need to search for it in CS-Script: https://github.com/oleg-shilo/cs-script/search?q=referencing
![image](https://user-images.githubusercontent.com/16729806/104603325-64d81080-56d0-11eb-8235-3ade77c795a1.png)

With 404, not sure what link was failing for you. This is the online documentation: https://www.cs-script.net/cs-script/help-legacy/root/. Though this is not Wiki but static pages and in some parts may be focusing on the legacy features. That's why it is "Legacy documentation" 

> Hmm. So how do I reference DLLs?

https://github.com/oleg-shilo/cs-script/wiki/CLI---User-Guide
![image](https://user-images.githubusercontent.com/16729806/104604024-1b3bf580-56d1-11eb-8298-9c2556c3001c.png)


> It allows you to do arbitrary transformations on your C# code before running it using "macros". For example, here's a macro ...

This is very similar to concept of precompilers that CS-Script supports natively:
This is an example of C++ style #DEFINE:
https://github.com/oleg-shilo/cs-script/blob/dbdcbe4bbe42a074c53efa662a49f38942ae3363/Source/deployment/samples/Precompilers/AdvancedSamples/CPPHashDef.cs#L1-L16

It is more advanced and less obvious feature that is better to learn through the examples:
https://github.com/oleg-shilo/cs-script/blob/master/Source/deployment/samples/Precompilers/AdvancedSamples

**Comment by qwertie** [comment]
No, that is not at all similar to EC# macros. If you think it is similar then tell me: how would you implement the `change_temporarily` feature I showed you in cs-script?

In EC# you can write this:

~~~cs
[ensures(# >= 0)]
static double Sqrt([requires(# >= 0)] double num) => Math.Sqrt(num);
~~~

which means this:

~~~cs
static double Sqrt(double num) {
	Contract.Assert(num >= 0, "Precondition failed: num >= 0");
	{
		var return_value = Math.Sqrt(num);
		Contract.Assert(return_value >= 0, "Postcondition failed: return_value >= 0");
		return return_value;
	}
}
~~~

So again please explain how you'd do this with cs-script?

**Comment by qwertie** [comment]
Or you could make a new kind of foreach-loop that keeps track of the index of the current item in the list:

~~~cs
define (for#($collection) { $(..contents); }) {
   {
      int it# = 0;
      foreach (var it in $collection) {
         $contents;
         it#++;
      }
   }
}

compileTime
{
	var sb = new System.Text.StringBuilder("I like ");
	for#(new[] { "french fries", "ice cream", "pizza" }) {
		if (it# != 0)
			sb.Append(" and ");
		sb.Append(it);
	}
}

const string likes = precompute(sb.ToString());
~~~

The output is:

~~~cs
const string likes = "I like french fries and ice cream and pizza";
~~~

**Comment by oleg-shilo** [comment]
> No, that is not at all similar to EC# macros. If you think it is similar then tell me: how would you implement the change_temporarily feature I showed you in cs-script?

Indeed I though it was similar. If you say it is not I am happy to accept that it was a mistake from my side.
