### ISSUE TITLE
vscode whether you can use right now. net5 csscritp ?

### ISSUE THREAD

**Issue by ananck** [oleg-shilo/cs-script#226]
How should I configure?

**Comment by oleg-shilo** [comment]
.NET5 is a .NET Core conceptually. Meaning that any IDE/Plugin that is targeting .NET Core is ready to deal with .NET5 runtime.
And VSCode is .NET Core ready (since Apr 8, 2020). So no config changes are required. Just install the extension and you are ready to go.

Saying that, a new .NET5 specific edition (final beta) of CS-Script is ready and available from Choco and this repo. Though I have only started updating the VSCode extension to specifically integrate with the latest CS-Script.

Thus you are days away from VSCode extension rand CS-Script itself being specifically ready and published for .NET5. Unless something unexpected happens. :)

**Comment by oleg-shilo** [comment]
Done. You can get it now from VSCode Extensions tab:

![image](https://user-images.githubusercontent.com/16729806/106351298-8e7b7380-632f-11eb-94ce-6af3fcf8c8fb.png)

**Comment by ananck** [comment]
![image](https://user-images.githubusercontent.com/32736265/106898563-501af580-672f-11eb-9f79-11c91c32304a.png)
![image](https://user-images.githubusercontent.com/32736265/106898867-ae47d880-672f-11eb-9806-a099ce269014.png)
![image](https://user-images.githubusercontent.com/32736265/106898076-b2bfc180-672e-11eb-8fed-cb04b969410f.png)


**question:**
1.cs-script 2.0 debug Not Responding;  
2.No code hints

**Comment by oleg-shilo** [comment]
Quite possibly you have a folder open in VSCode.

Use this as a guideline
https://github.com/oleg-shilo/cs-script.vscode#quick-start
