### ISSUE TITLE
How to dynamic load WinForm's Form

### ISSUE THREAD

**Issue by HalfasonYc** [oleg-shilo/cs-script#229]
I wanna load a form that containing three files, *.cs, *.resx, *.designer.cs. However, *.resx file load error. If not load *.resx file, normal.
How do *.resx files need to be loaded correctly? Thank you.

**Comment by oleg-shilo** [comment]
This issue has a sample in the first post.
The sample was used to illustrate the problem and to test the fix.

The problem is the WinForms do not consume resx files directly. Instead VS compiles them with the resource compiler into .resources file. 

The easiest way for you to is to use `.resources`:
```
//css_res MyApp.MyForm.resources;
```

You can also use `//css_res MyApp.MyForm.resx;` but in this case you need to ensure that the output `.resources` file name is specified as your form expects:
```
//css_resource <file>[, <out_file>];
``` 
The full help file is here https://github.com/oleg-shilo/cs-script/blob/master/help.txt
You can find the full description of the `//css_res` directive. 

You may also have a look at at this article: https://www.cs-script.net/cs-script/help-legacy/Using_Resources.html

**Comment by HalfasonYc** [comment]
thx, I did it successfully .

**Comment by HalfasonYc** [comment]
thx, I did it successfully .
