### ISSUE TITLE
Question: How to recompile?

### ISSUE THREAD

**Issue by jokabomo** [oleg-shilo/cs-script#230]
I want to re-compile some code when the user edits it. For example, they add or modify an existing function or class. I am using the VB.Net compiler in a C# application. When I try to recompile I don't get any errors but then try to run the recompiled code I get an error like:

> error BC30562: 'DoSomething' is ambiguous between declarations in Modules 'DXBScript.globals' and 'DXBScript.globals'.

Either that, or the previous code runs (from before recompile attempt) - like it is cached .
How can I either remove a VB module then add it back or just recompile it? I tried:

```
static System.Reflection.Assembly GlobalModule = null;
public static string AddGlobalCode(string code)
{
    string codeText =
@"Option Strict Off
Imports System
Imports sys=DXBScript.ScriptHelper
Namespace DXBScript
Public Module globals
" + code + @"
End Module
End Namespace";
    try
    {
        if (GlobalModule != null)
        {
            GlobalModule.UnloadOwnerDomain();
            // File is locked - cannot delete
            //if (System.IO.File.Exists(GlobalModule.Location))
            //{
            //    System.IO.File.Delete(GlobalModule.Location);
            //}
            CSScript.Evaluator.Reset();
        }
        GlobalModule = CSScript.LoadCode(codeText, null);
        return "OK";
    }
    catch (Exception ex)
    {
        return ex.Message;
    }
}
```
This function gets called at startup with saved code. Then again (multiple times) when user edits code.

**Comment by oleg-shilo** [comment]
Most likely the problem is cause by the fact that every time you call LoadCode you create a little assembly and load it in the current AppDomain.BTW that's why your file is locked and `UnloadOwnerDomain` does not do anything. It is designed to unload a remote domain but you are not creating a remote domain and executing the script in the current domain instead. 

Anyway, it's hard fro me to comment but most likely you can avoid collision by preventing your scriprt referencing loading all the assemblies of the current domain as it has multiple copies of your GlobalModule.

You are using older CSScript interface so I do not remember exactly the setting but I think it is `CSScript.RefereneceDomainAssembly`. You need to set it to false and reference the required assemblies explicitly.  I think `LoadCode` allows you to ass assemblies.

I would strongly recommend that you consider migrating to the evaluator interface and even possibly replacing VS with C# as the latest (.NET5 ) builds of CS-Script class library does note support VB, at least yet. 

I know it sound very drastic but declining relevance if VB makes it very difficult to justify the effort investment in this direction.
