### ISSUE TITLE
file recompilation problem

### ISSUE THREAD

**Issue by sebseyres** [oleg-shilo/cs-script#241]
Hi,
with the old version CSScriptLibrary.v3.5 i load file with this line CSScriptLibrary.CSScript.Load(csScript,dllFile, debugBuild: false);
If the file in csScript don't having change since the last compilation, the dllFile was load without recompilation( very fast)

Now, with the Net4.6 version i do that :
CSScriptLibrary.CSScript.LoadFile(csScript,dllFile, debugBuild: false); because the load methode is obsolete 
The problem is the file is always recompiled.
Is it a way to compile my file only if there is a change since the last loading?

Best regards
Seb

**Comment by oleg-shilo** [comment]
Will investigate. Thank you

**Comment by oleg-shilo** [comment]
I just realized that you are referring to the old pure .NET Framework targeting releases.
They have become effectively obsolete when MS decided to remove support for CodeDOM in all .NET Core (.NET5) editions.

Thus CS-Script had to drop support for Native interface (`CSScriptLibrary.CSScript.*`) and instead extend and evolve Evaluator interface (`CSScriptLib.CSScript.Evaluator.*`). 

Though the caching feature was not ported yet. That's why it is an enhancement as well.
Caching feature just has been implemented and will be available in the very next release.

```C#
dynamic script = CSScript.Evaluator
                         .With(eval => eval.IsCachingEnabled = true)
                         .LoadMethod(@"object print(string message)
                                       {
                                           Console.WriteLine(message);
                                       }");

script.print("Hello...");
```

Note the latest release (and all p.NET Core releases) are compiled as ".NET Standard 2.0" so the script engine nuget package can be used in both .NET and .NET Core host applications.
