### ISSUE TITLE
Upgrade issue 1.4.2 preview to version 2.0

### ISSUE THREAD

**Issue by RubberUK** [oleg-shilo/cs-script#243]
Hi Oleg,

When I upgrade from 1.4.2 preview to version 2.0 I get following error when my application is run.
This occurs after the first script is run successfully and I navigate to a new page.
It feels like CSScript is changing some paths???

System.Exception
  HResult=0x80131500
  Message=The component 'Toronto.Modules.Views.Login.LoginView' does not have a resource identified by the URI '/Toronto.Modules;V21.1.4.0;component/views/login/loginview.xaml'.
  Source=PresentationFramework

Any help is much appreciated.

Many  Thanks,
Nathan.

**Comment by oleg-shilo** [comment]
Not sure the issue details are accurate. The current version is v4.0.2.0
![image](https://user-images.githubusercontent.com/16729806/121885651-bc4ddb80-cd57-11eb-8d4f-0b68f11b8756.png)

**Comment by RubberUK** [comment]
Hi Oleg,

I get the same behaviour when I update to cs-script 4.0.1.

**Comment by oleg-shilo** [comment]
OK, then can you send me a "hello world" stile test project that exhibits the problem and I will have a look.

Most likely there is a problem locating the compiled script when it is to be loaded after it was executed once.
If it is the case then you can temporary address the problem by disabling the caching: `csws -c:0 your_script.cs`

But in order to **fix** the problem I need to have a look at the runtime behavior. So the test project is essential.

Thank you.

You can also have a look at the default WPF script sample:
_Create sample:_
```ps
cscs -new:wpf test.cs
```
_Execute sample:_
```ps
csws test.cs
```

**Comment by RubberUK** [comment]
Hi Oleg,

Setting CSScript.EvaluatorConfig.RefernceDomainAsemblies = false has fixed the issue.

Many Thanks,
Nathan.

**Comment by oleg-shilo** [comment]
Thank you for letting me know.

It was not clear if you are hosting the engine (as you do with CSSCriptLib.dll) or use it as CLI (cscs.exe). So I assumed you were using cli.

anyway, glad it's all sorted out.
