### ISSUE TITLE
.Net 5 SDK project, could not run "CompileAssemblyFromCode"

### ISSUE THREAD

**Issue by apoznanskiy** [oleg-shilo/cs-script#245]
When I try to run "CodeDomEvaluator.CompileAssemblyFromCode" in project with .net 5 and RuntimeIdentifier = win10-x64 property set in project file I get exception that csc.exe not found. I made small research and found out that it is looking for csc.exe in my Debug folder.Is .net5 under win10x-64 is also core?(cause as I saw it uses different csc because of this) Mb I'm doing something wrong and I should not use CodeDomEvaluator?
[Test CSSript.zip](https://github.com/oleg-shilo/cs-script/files/6711566/Test.CSSript.zip)

**Comment by apoznanskiy** [comment]
Figure out how to workaround this, need to set SelfContained to false in project file(with RuntimeIdentifiers specified it is true by default). But what about case with SelfContained version of app with CSScript is it possible to use it in this case?

**Comment by oleg-shilo** [comment]
It is a very interesting problem.

`CodeDom` evaluator engine relies on the .NET compiler executable `csc.exe` which is a part of .NET 5 SDK. It is located in the the same folder where `System.Private.CoreLib.dll` assembly is. 

CS-Script is using this routine to locate `csc.exe`:

```C#
csc_file = Path.Combine(Path.GetDirectoryName("".GetType().Assembly.Location), "csc.exe");
```
In you case the the set of all .NET assemblies and .NET runtime itself is aggregated in the same folder where your built executable is. Of course `csc.exe` cannot be found there as .NET apps compiled as SelfContained do not include any compiling tools (e.g. _dotnet.exe_ or _csc.exe_ in the output folder).

From this prospective you are not even running your app on .NET (.NET Core specifically) as even if it is present on your system it is not used to host you app. Instead it is hosted  by a native process that loads a very trimmed leaned version of .NET runtime with only .NET assemblies that our app may need during the execution. That's why `Runtime.IsCore` returns _false_. 

Thus the script engine behaves exactly as it supposed to do but... it does not throw the informative exception. And this needs to be fixed. That's why I marked the this issue as "enhancement".

> But what about case with _SelfContained_ version of app with CSScript is it possible to use it in this case?

Technically speaking you can set location of csc.exe if it is present in some other location (e.g. .NET 5 SDK folder):
```C#
Environment.SetEnvironmentVariable("css_csc_file", "<csc.exe path>");
```
However even if it works on the build system it's not a good approach as the usual reason for building _SelfContained_ is that the target system for the app does not contain SDK so _csc.exe_ will not be available.

Thus the only right way to do solve this is to use the default evaluator engine Roslyn, which is always included in the CS-Script nuget package .

Either:
```C#
CSScript.EvaluatorConfig.Engine = EvaluatorEngine.Roslyn;
. . .
var asm_file = CSScript.Evaluator...
```
Or:
```C#
var asm_file = CSScript.RoslynEvaluator...
```
I checked your sample and it works just fine with Roslyn.




 does not require is not
