### ISSUE TITLE
Assembly-duplication in AppDomain when getting RoslynEvaluator increased after updating from 1.4 to 2.0

### ISSUE THREAD

**Issue by X39** [oleg-shilo/cs-script#251]
I just recently updated to CS-Script 2.0 and discovered something rather weird,
the reflection methods I wrote ages ago just randomly seemed to be broken.
After further investigation, I noticed that some assembly was loaded twice. At that point, I assumed that it just was a build error with the same assembly being referred twice (making use of runtime assembly loading). Today it happened again, this time however i noticed a pattern.
The assemblies in question would only be loaded twice when actually prior calling the state-machine i created, that makes heavy use of CS-Script.

After investigating with some debug methods (see calls.txt), i quickly noticed that CS-Script massively duplicates assemblies in the current AppDomain (see v2-0.txt) and after comparing it to the 1.4 version (see v1-4.txt) things got worse.

The issue i now face is that due to this pretty much all reflection i utilize to build Expression trees and what not is broken once i upgrade to 2.0 and i am not entirely sure if it is due to some misshab of mine.

The configuration i do is pretty much nothing, the lines listed in `calls.txt` plus a `CSScriptLib.CSScript.EvaluatorConfig.DebugBuild = true;` if DEBUG is defined is all setup i do.

[v1-4.txt](https://github.com/oleg-shilo/cs-script/files/6962599/v1-4.txt)
[v2-0.txt](https://github.com/oleg-shilo/cs-script/files/6962600/v2-0.txt)
[calls.txt](https://github.com/oleg-shilo/cs-script/files/6962602/calls.txt)

**Comment by oleg-shilo** [comment]
This is the result of the CLR design limitation that was in the .NET Framework for years: once assembly loaded it cannot be unloaded. Meaning that if you execute too many scripts your `AppDomain` becomes oversaturated with the loaded assemblies.

CS-Script provided it's own work around through a simplified `AppDomain` unloading. Even though it was not ideal.
Additionally CS-Script runtime was by default doing script assembly caching to lower the assembly loading pressure.

In case of .NET Core (CS-Script 4.0.0+) the situation was the same but with some later changes the finally provided a native unloading approach. And caching is still available even though it is now disabled by default due to some reports that it may lead to some undesired side effects that have been introduced in .NET Core.

Thus your options are:
- Completely take the charge of script assembly loading by executing the scripts from the temp domain and then unloading it. The way .NET Framework recommended way.
- Use brand new feature of .NET Core CLR for truly unloading the assemblies:  
```C#
[Fact]
public void call_UnloadAssembly()
{
    dynamic script = CSScript.RoslynEvaluator
                                .With(eval => eval.IsAssemblyUnloadingEnabledled = true)
                                .LoadMethod(@"public object func()
                                        {
                                            return new[] {0,5};
                                        }");

    var result = (int[])script.func();

    var asm_type = (Type)script.GetType();

    asm_type.Assembly.Unload();
}
```

- Enable caching as it may completely solve your problem. It will depend on your specific scsnario:
```C#
dynamic printerScript = CSScript.Evaluator
                                 .With(eval => eval.IsCachingEnabled = true)
                                 .LoadFile(script_file);
```
