### ISSUE TITLE
//css_ref does work with CodeDom

### ISSUE THREAD

**Issue by rp0815** [oleg-shilo/cs-script#299]
Using Evaluator.CodeDom I'm getting a problem with //css_ref. I add e.g. a //css_ref System.Net.Http and use a HttpClient in the code. But, I get an error CS0246: The type or namespace name 'HttpClient' could not be found (are you missing a using directive or an assembly reference?)

While debugging I found out that the //css_ref System.Net.Http is resolved by the AssemblyResolver to C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Net.Http.dll. This entry is pulled out in CodeDomEvaluator.CompileAssemblyFromFileBatch because this location is not GAC (which would be C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll).

I guess this behaviour is same for all //css_ref.

I attached a solution to test it. When running the WpfApp start the script TheThirdScript which wants to use HttpClient.

[cs-script_.299.zip](https://github.com/oleg-shilo/cs-script/files/8861872/cs-script_.299.zip)

**Comment by oleg-shilo** [comment]
The problem is caused by the System.Net.Http.dll not being resolved accurately because it is in GAC and probing is no longer available in .NET. 
It was available via fusion.dll as an undocumented feature in older .NET but .NET Standard does no longer support it. Thus CS-script has resorted to the poor-man GAC probing by simply looking for the DLLs in the .NET bin folder (e.g. `C:\Windows\Microsoft.NET\Framework\v4.0.30319`). This is the routine:

https://github.com/oleg-shilo/cs-script/blob/ac885f8042dbe0ceb18f0f87ef8236a019b13894/src/CSScriptLib/src/CSScriptLib/AssemblyResolver.cs#L140-L147

All .NET GAC DLLs are located there anyway. and even if you compare two System.Net.Http.dll files in question you will see that they are identical:

![image](https://user-images.githubusercontent.com/16729806/173071324-23412436-d7ce-42fd-ad78-88c0f6d9234a.png)
 
This means that while the correct assembly file was found, its location does not allow csc.exe to reference it successfully. Why? I cannot tell. It is really the mystery of csc.exe and assembly probing there.

How to deal with it?
The most reliable way is to reference the problematic assembly explicitly:

```C#
NetCompiler.EnableLatestSyntax();

var script = CSScript.CodeDomEvaluator
                        .ReferenceAssemblyOf<HttpClient>() // this line will do the trick
                        .LoadCode(@"
                                    //css_ref System.Net.Http.dll
                                    using System;
                                    using System.Net.Http;

                                    public class Test
                                    {
                                        public void Foo()
                                        {
                                            using (var client = new HttpClient()) { }
                                        }
                                    }");
```
Though there is even a more interesting (even though less deterministic) mechanism for that. You can add the GAC dir to the search dirs and its location will be picked first. Exactly what we need. 

I even added your very use case in the distributable samples: 

https://github.com/oleg-shilo/cs-script/blob/284be74392a2ae2b52df4eabea2340b48115a1b7/src/CSScriptLib/src/Client.NET-Framework%20(CodeDom)/Program.cs#L48-L68

**Comment by oleg-shilo** [comment]
Updating your script with `//css_dir C:\Windows\Microsoft.NET\assembly\GAC_MSIL\**`  did not help right away. Probably something different in the script setup. But you now have the sample code that works, so you will be able to trace it:  https://github.com/oleg-shilo/cs-script/tree/master/src/CSScriptLib/src/Client.NET-Framework%20(CodeDom)

**Comment by oleg-shilo** [comment]
Actually, it works just fine after fixing the mistake in the `TheThirdScript.cs` file (attached).

[TheThirdScript.zip](https://github.com/oleg-shilo/cs-script/files/8879676/TheThirdScript.zip)
