### ISSUE TITLE
.config file missing in installer

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [oleg-shilo/cs-script#3]
In order to install CSScript I had to manually addthe file `css_config.exe.config` containing:
```XML
<configuration>
   <runtime>
      <loadFromRemoteSources enabled="true"/>
   </runtime>
</configuration>
```

Please add it to the installer package to avoid errors

**Comment by oleg-shilo** [comment]
Ironically the early releases relied heavily on *.exe.config file but I had to abandon this approach as it enforced certain policies (e.g. loadFromRemoteSources) on the target PC without user consideration.

But I would resurrect .exe.config if it's absence is causing a major problem that cannot be solved by other means. 

Can you tell me what exactly happening in your case. Is in your case you downloaded the binaries from the internet and they got locked by Windows? Though the rest of the binaries would be locked too...
How exactly you got the binaries on your PC? Do you invoke css_config.exe remotely?

**Comment by gabriele-ricci-kyklos** [comment]
I downloaded the binaries from https://csscriptsource.codeplex.com/releases. Then I try to install CSScript by clicking on the `install.cmd` batch, and I got
```
System.IO.FileLoadException: Could not load file or assembly 'file:///C:\cs-script\csws.exe' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\cs-script\csws.exe' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=131738 for more information.

in System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
in System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection, Boolean suppressSecurityChecks) 
in System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
in System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)
in System.AppDomain.ExecuteAssembly(String assemblyFile, String[] args)
in AppForm.StartConfig()
```

So I read about `loadFromRemoteSources` and the way to enable it was to add a config file as the one I posted above, so I did it and the installer started

**Comment by oleg-shilo** [comment]
Thank you. But what utility did you use to unpack *.7z? 
Was it the default Windows explorer integrated handler or WinRar? Or Something else?

**Comment by gabriele-ricci-kyklos** [comment]
I don't think the files were blocked by windows if that's what you think. I used WinRaR anyway

**Comment by oleg-shilo** [comment]
Thank you. Then it WAS WinRar! 

And yes I am implying the files were and probably still locked. Unfortunately WinRar has been already reported to me as an "offender". That is why in "How to install CS-Script on Windows" I nominate Chocolate (Windows apt-get) as a preferred way of deploying CS-Script and 7Zip as a recommended utility for unpacking if one decides to install manually.

Now your feedback prompted a few changes that I will need to implement:
- I will update the root\readme.txt with the warning against WinRar and the advise to use Chocolatey
- I will add css_config.exe.config into distro as a prevention measure. I tested it and indeed it eases the pain by allowing execution of the blocked content. Though it doesn't solve the problem the content remains blocked. Can you verify please that in the file properties the executrices are still marked as blocked on you PC. 
- I also updated CodeProject releases page to indicate that that latest releases should be taken from GitHub. GitHug release notes are also updated to reflect preferred deployment techniques.

And as for your case I suggest that you uninstall the version that you have right now as it is an old release anyway. And you can use [Chocolatey](https://chocolatey.org/) to get the latest release as it doesn't lock any files. Otherwise use [GitHub releases](https://github.com/oleg-shilo/cs-script/releases).

**Comment by gabriele-ricci-kyklos** [comment]
Actually yes, the files are still blocked. I will try to download the latest github release and unpack it with 7z
