### ISSUE TITLE
Please make a V3 version that is built against .NET Framework 4.8

### ISSUE THREAD

**Issue by UweKeim** [oleg-shilo/cs-script#324]
While I do understand that the [last V3 release](https://github.com/oleg-shilo/cs-script/releases/tag/v3.30.5.2) that runs on .NET Framework, is more than two years ago now and you prioritize the .NET Core based CS-Script, I still have a large script base that is actively running and using V3.

My new scripts will be developed against V4, but for the tons of other scripts I want to stay with V3 (e.g. because auf WSDL bindings).

Yesterday, the [morelinq](https://github.com/morelinq/MoreLINQ) NuGet package, that I use in my CS-Script scripts, was automatically updated to 3.4.0 which broke the usage of it in CS-Script V3:

> https://github.com/morelinq/MoreLINQ/pull/843#issuecomment-1448947915

### My question

Would it be possible that you "simply" release yet another version of V3 that is built against .NET 4.8 or .NET 4.8.1?

I don't know how much effort this would take or if it is a simple rebuild against the newer .NET Framework version.

In any case you would help me tremendously. Thanks a lot in any case 🙂

**Comment by oleg-shilo** [comment]
Hi Uwe,

Unfortunately, it is impossible. 

The problem is that .NET Core API is not compatible with .NET Framework. It's just impossible to rebuild the old codebase.
I know that it is quite impactful for some users but it's not something that I have control over. >NET Team has made this decision and we are all to deal with it :( 

Though I have made the V3 Class Library beating built as .NET Standard, meaning that it can be hosted in .NET Framework applications. But of course, in such scenario, some .NET Core-specific features will not be available. And the V3 CS-SCript API is different even though conceptually very similar. 

If it is indeed that important, then it's possible just to recompile the last V3 .NET Framework codebase against any CLR version. The project is now moved to the dedicated repository: https://github.com/oleg-shilo/cs-script.net-framework
 The code base is equivalent of ([v3.30.5.2](https://github.com/oleg-shilo/cs-script/releases/tag/v3.30.5.2))
 
Is it what you are looking for?

**Comment by UweKeim** [comment]
Thanks, Oleg,

Recompiling the last V3 .NET Framework codebase against the 4.8.1 CLR seems indeed to be what I'm looking for.

Will try this if I come across such an issue again.

**Comment by oleg-shilo** [comment]
I have made a https://github.com/oleg-shilo/cs-script.net-framework/releases/tag/v3.30.6.0 release, which is an equivalent of the v3.30.5.2 but recompiled for .NET v4.8

**Comment by UweKeim** [comment]
Wow, incredible. Thanks a million times, @oleg-shilo!
