### ISSUE TITLE
`CSScript.Evaluator.LoadCode` broken on net48 after cs-script 4.8.3

### ISSUE THREAD

**Issue by Cryolitia** [oleg-shilo/cs-script#362]
I have been maintaining an old WPF program. I tried to upgrade NuGet packages today, and `CSScript.Evaluator.LoadCode` occurred the exception below. After a quick bisect, I found that it works with cs-script 4.8.1 and broken with cs-script-4.8,3. I have tried `CSScript.Evaluator.Eval` with 4.8.3 but the same fault.

```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=未能加载文件或程序集“System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。系统找不到指定的文件。
  Source=CSScriptLib
  StackTrace:
   在 CSScriptLib.RoslynEvaluator.Compile(String scriptText, String scriptFile, CompileInfo info)
   在 CSScriptLib.EvaluatorBase`1.CompileCode(String scriptText, String scriptFile, CompileInfo info)
   在 CSScriptLib.EvaluatorBase`1.LoadCode(String scriptText, Object[] args)

```

**Comment by oleg-shilo** [comment]
Sadly Roslyn can no longer work on .NET Framework.
With the latest releases of CS-Script I had to upgrade Roslyn packages and it requires the new version of System.Runlime.Loader that is not available for .NET Framework hosting environment.

.NET team admitted that they should have raised `NotSupportedException` instead of `FileNotFoundException`.
You can find more info here: https://github.com/dotnet/runtime/issues/22732

What it means is that it's not possible to actually fix it and your options are one of these:
- Use an older version of CS-SCript that has no dependency on .NET Core loader
- Migrate your WPF project to .NET and the latest CS-Script will work on it fully. 

I know it's not the answer you were looking for but it is the unfortunate consequence of relying on some legacy stuff (e.g. .NET Framework). I have also been the victim of that.

I have updated the old code samples with the description of the problem.

**Comment by Cryolitia** [comment]
So sad about it, I would consider to upgrade .Net but still wish to support Windows 7 users. /sad

**Comment by Cryolitia** [comment]
> I though you could have .NET (core) on Win7. Am I wrong?

With a runtime even bigger than my program itself. Thank for your help, I would consider it.

**Comment by oleg-shilo** [comment]
I forgot another option:

- You can run it under .NET Framework but against the `csc.exe` compiler (not Roslyn-scripting).

If you do not care about new C# syntax (C#6 and higher)  then you can achieve a performance that is even better than on .NET Core (no extra dependency required):


![image](https://github.com/oleg-shilo/cs-script/assets/16729806/f07ab47e-c209-4ad2-bd09-2c362620b8e9)

I just committed the change required for that. Will release the feature next week.

**Comment by Cryolitia** [comment]
that's great

**Comment by oleg-shilo** [comment]
I have reopened this issue and will close it after the update is released. 
I have done the actual change so it is only a matter of making the release.
The solution will is captured in this sample:
https://github.com/oleg-shilo/cs-script/blob/master/src/CSScriptLib/src/Client.NET-Framework%20(CodeDom)/Program.cs

**Comment by oleg-shilo** [comment]
Done: https://www.nuget.org/packages/CS-Script/4.8.14

`dotnet add package CS-Script --version 4.8.13`

**Comment by Cryolitia** [comment]
With 4.8.14.0 occures this fault
![image](https://github.com/oleg-shilo/cs-script/assets/23723294/1ed039c6-951f-4d2b-babd-bc0702e90731)

test code

```
_binding.FileProcessor = (IFileProcessor) CSScript.CodeDomEvaluator
                 .WithRefAssembliesFilter(asms => asms.Where(a => !a.EndsWith("System.Core.dll") &&
                                                                  !a.EndsWith("Systemdll"))).LoadCode(code);
```

**Comment by oleg-shilo** [comment]
This is now your functional error, not the assembly loading one.

Use the example I shared as a starting point and you will see what in your code is causing the problem. Because of the "unsupported operation" you may be trying to execute the script that requires the assembly you have not referenced.

**Comment by Cryolitia** [comment]
![image](https://github.com/oleg-shilo/cs-script/assets/23723294/8b2b8f4f-fe23-4e04-a573-54f80c5d0141)

it doesn't work, I put the demo code in `System.Windows.Application::OnStartup`

**Comment by Cryolitia** [comment]
resolved
