### ISSUE TITLE
Assembly not found exception

### ISSUE THREAD

**Issue by Alpini1980** [oleg-shilo/cs-script#365]
Hi,

I installed Version 4.8.14 via NuGet in Visual Studio Community 2022 but the CSScript.Evaluator.LoadCode<>() immediately throws an exception:

System.IO.FileNotFoundException: "Die Datei oder Assembly "System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden."

Sorry for German language exception it can be translated as "file or assembly or one of it's dependencies not found exception". 

As a dependency the System.Runtime.Loader 4.3.0 was installed as NuGet package. 

----

If I switch to CS-Script Version 3.30.5.1 with the System.Runtime.Loader 4.0.0 I get an other exception in the same line as above:

System.MissingMethodException: "Der Konstruktor für den Typ "Microsoft.CodeAnalysis.EmbeddedAttribute" wurde nicht gefunden."

This one is a "constructor not found exception".

I would be very grateful for any advises.

Regards, Stefan

**Comment by oleg-shilo** [comment]
I have just created the project as you described. Seems to work (see attached sample):
![image](https://github.com/oleg-shilo/cs-script/assets/16729806/6bdfb3bc-5752-4c23-9665-2cff42d11e47)

[ConsoleApp8.zip](https://github.com/oleg-shilo/cs-script/files/14190579/ConsoleApp8.zip)

**Comment by Alpini1980** [comment]
Hi,

I found the problem. I did not read that .net 5.0 is required at least and installed it in a .net Framework 4.8 project . So this issue can be closed. Next try when we upgraded our project to .net 5.0 but at moment my team members won't do it. 

Should the CS-Script.bin 3.30.5.1 work on .net Framework 4.8? It tried it too but also got a dependency not found exception for Microsoft.CodeAnalysis.Scripting.dll

Regards, Stefan

**Comment by oleg-shilo** [comment]
These two sample projects show how to use (though with some limitations) CS-Script .NET Core build on .NET FX host:
![image](https://github.com/oleg-shilo/cs-script/assets/16729806/54e67034-be55-4817-ba6e-7288798c7e74)

You can also try a deprecated .NET FX stream ob .NET FX: https://github.com/oleg-shilo/cs-script.net-framework/releases/tag/v3.30.7.0.

Since MS abandoned .NET FX, I have stopped evolving CS-Script targeting this runtime. So that stream is about 2 years behind in terms of functionality with some minor updates done a few months ago.  

While it is still fully functional, it is effectively out of support. Thus your best bet is to have a roadmap for the .NET Core transition.

**Comment by Alpini1980** [comment]
Hello Oleg,

thank you - that sounds very interesting and I would like to give it a try. Where do I find the .net Framework sample projects? If it was the link behind your screenshot - it leads to a 404 Error. I tried to find the samples in the old https://github.com/oleg-shilo/cs-script.net-framework repo without luck.

And of course I fully understand that you don't want to waste your energy into developing the old version any longer.

**Comment by oleg-shilo** [comment]
It's OK, you just clone the code and samples are part of the codebase. In both core and fx repos. You just change startup project and then you can run/debug it as any other VS proj.

**Comment by Alpini1980** [comment]
Hello Oleg,

thank you very much for your support. I got it working (also in my own Framework project).

Regards, Stefan
