### ISSUE TITLE
cs-script does not support MAUI Android

### ISSUE THREAD

**Issue by kimdiego2098** [oleg-shilo/cs-script#379]
I tried using this code and found an error in maui Android

```
CSScript.Evaluator.Eval("6/3");
```

Error message:

```
System.Reflection.TargetlnvocationException:Exception has been thrownby the target of an invocation.
: 
SystemNotlmplementedException: The method or operation is not implemented.
at 
System.Reflection.Assemblyget_GlobalAssemblyCache()
at
CSScriptLib.EvaluatorBase~1.<>c

```

So  cs-script support maui  or not?

**Comment by oleg-shilo** [comment]
A simple answer is no, your environment does not support scripting. It's not even CS-Script it is your .NET runtime that does not support Roslyn and other more advanced features present in other .NET distributions.

Though it is my educated guess, not the knowledge as I cannot test it right now.

I suggest a very simple experiment. You can disable this very valid call by disabling referencing appdomain assembly:

```c#
CSScript.EvaluatorConfig.ReferenceDomainAssemblies = false;
```

This will let your through the failings step but most likely it will fail when it tries to invoke Roslyn.

Try and let me know how did you go.

 

And it's not for CS-Script reason but for .NET.

**Comment by kimdiego2098** [comment]
```
CSScript.EvaluatorConfig.ReferenceDomainAssemblies = false;
```

After configuration, it can take effect and run normally in Android.

How was this achieved?

**Comment by kimdiego2098** [comment]
What impact will this config ? I should understand it to prevent errors in other features of the project

**Comment by oleg-shilo** [comment]
_**How**_
> After configuration, it can take effect and run normally in Android.

Wow, excellent,  It's not what I expected as for years Roslyn was only available on the full scale (e.g. desktop/server) runtimes.  

The setting that you changed controls automatic assembly referencing. IE by default your script automatically references all assemblies currently loaded in the app domain including the host (your application). This way your script can call any method from your host app without any extra effort.  

When the auto referencing is is performed all AppDomain assemblies analyzed and global cache assemblies are filtered out. You do not need to reference them as they are always available anyway. The filtering involves checking the property `Assembly.GlobalAssemblyCache` and... on Android this property is not implemented and throws the exception. Thus by switching off the whole auto referencing AppDomain assemblies you simply prevented the execution route that calls `Assembly.GlobalAssemblyCache`.

**_The impact_**
Because AppDomain assemblies are no longer referenced you have to reference them explicitly if you need to call any method of that assembly type. 

You can either reference all of them explicitly but when you do that you need to ensure that the GAC assessment is not performed. The appropriate call for that is this:

```c#
dynamic script = CSScript.RoslynEvaluator
                         .ReferenceDomainAssemblies(DomainAssemblies.AllStatic)
                         .LoadMethod(@"public (int, int) func()
                                        {
                                            return (0,5);
                                        }");

(int, int) result = script.func();
```

Or you can reference one by one only the assemblies that you need. This is how you can reference host assembly (executing assembly):

```c#
dynamic script = CSScript.RoslynEvaluator
                         .ReferenceAssembly(Assembly.GetExecutingAssembly())
                         .LoadMethod(@"public (int, int) func()
                                        {
                                            return (0,5);
                                        }");

(int, int) result = script.func();
```
--------------

Nevertheless, it is a defect. The script engine should handle the cases when `Assembly.GlobalAssemblyCache` is not implemented.
I have done the fix already so I will be publishing the HotFix patch tomorrow.

**Comment by kimdiego2098** [comment]
thanks, it solved my doubts very well !

**Comment by oleg-shilo** [comment]
Done.
You can update your package:

```ps
dotnet add package CS-Script --version 4.8.18-HotFix
```
