### ISSUE TITLE
using statement vs using declaration

### ISSUE THREAD

**Issue by johngardner58work** [oleg-shilo/cs-script#386]
Regarding the following
`if (...) 
{ 
   // does NOT work in CS-Script but works in C# 8.0 and up.  Note I was using .NET interactive
   using FileStream f = new FileStream(@"C:\users\jaredpar\using.md");
   // statements
}

// Is equivalent.   This works in CS-Script
if (...) 
{ 
   using (FileStream f = new FileStream(@"C:\users\jaredpar\using.md")) 
   {
    // statements
   }
}`

**Comment by oleg-shilo** [comment]
This can be caused by the script engine using the older version of C# compiler which does not support that new way of declaring `using`.  Though, if you are using the latest >NET SDK and CS-Script then it all is fine:

![image](https://github.com/user-attachments/assets/bf8059a0-d722-4418-b656-1baa4f93bf03)

Update the script:
![image](https://github.com/user-attachments/assets/9deaf0db-cbaa-435d-9678-4b7e933aac8b)

And now check and execute it:
![image](https://github.com/user-attachments/assets/fbfb4520-31d3-49c2-ba54-e689dcd86012)

If you want a faster compilation you can redirect the script engine to the csc.exe C# compiler:
![image](https://github.com/user-attachments/assets/182e13e6-3934-4516-a053-a504e5bdc824)
