### ISSUE TITLE
Custom CS-Script file extension for simple double-click execution of scripts.

### ISSUE THREAD

**Issue by shawnlawe** [oleg-shilo/cs-script#49]
Have you considered supporting custom file extensions for CS-Script files? For example ".csexec" instead of ".cs"? That way CS-Scripts could be configured to automatically run when double clicked, instead of opening in Visual Studio.

It is easy enough for me to associate ".csexec" files on my system with your script engine, but then I lose all the CS-Script context menus such as "Open in Visual Studio", etc. It would be great to have the best of both worlds. I find it silly to always have to create batch files to make launching my CS-Scripts as painless as possible for myself and end-users in particular.

**Comment by oleg-shilo** [comment]
You have a few options here:
* right-click .cs select CS-Script > Run
* rename .cs into .csx and this one can be double-clicked + all shell extensions are still supported
* enable double-clicking for .cs files:
![image](https://cloud.githubusercontent.com/assets/16729806/23576498/1e781d9e-00fb-11e7-96ef-bfa63301b091.png)

**Comment by shawnlawe** [comment]
Thanks for the response. I updated my CS-Script version and now I can double-click .csx files as you suggested. :)

This solution is almost perfect. The only problem is that if I use the CS-Script Open With Visual Studio command, the file is still a .csx file which Visual Studio doesn’t recognize so I don’t get intellisense or syntax highlighting. It would be ideal if CS-Script could temporarily rename the file to make Visual Studio happy or even create a hard link to a renamed version for Visual Studio.

**Comment by oleg-shilo** [comment]
You probably missed it.

In me prev post I gave you the options and one of them was to make .cs to run on doubleclick (option 3 in the bullet point list). This way your requirement is fully satisfied. It is not **my** prefered option but many users like it.

**Comment by shawnlawe** [comment]
Sorry I guess I misunderstood when you said rename .cs into .csx and "all shell extensions are still supported". The Open With Visual Studio one isn't really "supported" as it doesn't work. I'm thinking I might try updating the "debugVSxxx.cs" files in the lib folder to recognize when the file is a .csx file and create a hard link to a .cs version of the file so Visual Studio will recognize it.

Thanks again for the suggestions and keep up the awesome work!

**Comment by oleg-shilo** [comment]
OK, my mistake. Renaming doesn't do the trick alone. You will need to enable shell-extensions support for non-cs files. Don't bother with `debugVSxxx.cs` it is involved in handling but not triggering shell-extensions menus. This is how it works:

- Open CS-Script config console. 
- Ensure Shell extensions are enabled by toggling a few times "Use Advances Shell Extensions". Toggling will repare them if they are broken.
![image](https://cloud.githubusercontent.com/assets/16729806/23817976/6700d128-064b-11e7-88f5-3fe666e4a626.png)
- Check "Use for all file extensions". This will extend the support for *.csx files. 

This will help with the *.csx files but of course this will not change the fact that VS doesn't understand .csx files.

Anyway, I still think that the most direct solution for your problem is just to change the double-click action for .cs files. Just change it from `Notepad++` to `<run>`:
![image](https://cloud.githubusercontent.com/assets/16729806/23818155/b95278ea-064c-11e7-9b4c-544e105ec7cf.png)
