### ISSUE TITLE
If feasible, add an option to select the C# language specification to be used

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#51]
Currently, the C# language specification seems to be limited to a certain version. In my case (still using "\lib\Bin\NET 3.5\CSScriptLibrary.dll") the C# version seems to be limited to C# 2.0 or below. I have tried to specify C# 4.0 using "/langversion:4" but get this exception:
```
csscript.CompilerException: (0,0): error CS1617: Invalid option '4' for /langversion; must be ISO-1, ISO-2 or Default
```
This fact limits the way scripts can be written, e.g. it is not possible to write scripts that use default parameter specifiers such as:
```
int MethodWithOptionalParameter(int value = 0)
{
	return (value);
}
```
I assume that "\lib\Bin\NET 4.0\CSScriptLibrary.dll" does support C# 4.0 and I will  sooner or later will upgrade to .NET 4.0. Still, I'd like to select the C# language specification independently on the .NET Framework version. After all, that's exactly what Visual Studio is doing. VS2015 e.g. supports C# 6.0 (which of course includes C# 4.0 and thus default parameter specifiers) even though my project still targets the .NET 3.5 Framework. And the very same issue might re-appear in the future, when e.g. C# is 8.0 but my application still targets the .NET 4.5 Framework.

**Comment by oleg-shilo** [comment]
Unfortunately it's not that simple. 

The `/langversion` does not control what syntax is supported but rather validates the input syntax withing what compiler can understand.

The MS compiling services that CS-Script is using effectively adhere to the host application runtime version. Why? Because if you manage to use C# 5 (.NET 4.0) syntax the compiled script/assembly will not load in your .NET 3.5 host as it will be a .NET 4.0 assembly.

Thus if you want to support C# 5 (.NET 4.0) then you need to develop your hos app as .NET 4.0 assembly and use .NET 4.0 CS-Script build. 

However you can use C# 6 syntax on .NET  4.0 host as both C# 5 and C# 6 emit assembly targeting the same CLR (v4.0).

Though because MS failed to include C# 6 compiler in the default distribution it needs to be added explicitly:
```C#
//Add C# 6 syntax support, otherwise scripts will be treated as C# 5
CSScript.GlobalSettings.UseAlternativeCompiler = @"%CSSCRIPT_DIR%\Lib\CSSCodeProvider.v4.6.dll";
``` 
Or you can use `CSScript.RoslynEvaluator` which uses Roslyn the same way as `%CSSCRIPT_DIR%\Lib\CSSCodeProvider.v4.6.dll` does.

**Comment by maettu-this** [comment]
OK, got it. Then this is indeed a limitation that can only be overcome by upgrading the runtime. I will document this in my hosting application to keep it in mind. Thanks for the explanation.
