### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by gitlsl** [oleg-shilo/cs-script#58]
`Scripting.Extensions  UnloadingSamples().RunAll()`  will throw error `complie error`?
also I have a question:
 can `CodeDOM` load code into current domain and unload it? I can not understand what difference between the three engines because both of them can unload by remote domain

**Comment by oleg-shilo** [comment]
>Scripting.Extensions UnloadingSamples().RunAll() will throw error complie error?

I am guessing you are referring to the runtime error in `LoadCodeRemotely`. The error is caused by the older sample being included in the package by mistake. Even though the sample source under source control is the correct one.

The correct sample includes this extra code:
```
//This use-case uses Interface Alignment and this requires all assemblies involved to have 
//non-empty Assembly.Location 
CSScript.GlobalSettings.InMemoryAssembly = false;

var script = CSScript.CodeDomEvaluator
...
```
Your code should work with the correction above. 
The latest NuGet package samples have been updated.

>can CodeDOM load code into current domain and unload it?

No, none of the tree supported engines (CodeDOM, Roslyn, Mono) can unload the code (assembly) from the current domain. It is a .NET limitation. Though CS-Script provides a "work-around" API for loading the script into a **remote** but not current appDomain. And the possibility of unloading this remote app domain.

**Comment by gitlsl** [comment]
Ok cs-script  provides a "work-around" API  to unload remote domain for 3 engines and only CodeDomEvaluator  has a cache ability

**Comment by oleg-shilo** [comment]
Correct. 

Only CodeDOM can produce an assembly file so it can be cached. The other engines produce pure in-memory assemblies that is not possible to cache. This file-less nature of Roslyn and Mono is also a reason why debugging the scripts is only possible for CodeDOM compiled scripts - debuggers need the assembly file. 

However  the actual compilation phase with CodeDOM can be slower comparing the other two engines.

And when it comes to comparing Roslyn vs Mono then today (after VS2017 is out) it's easy. Mono is a discontinued effort so it does not support neither C# 6 nor C# 7 syntax. Roslyn does.

The whole subject of engine differences is covered pretty well here: https://github.com/oleg-shilo/cs-script/wiki/Choosing-Compiler-Engine

**Comment by gitlsl** [comment]
thank you
