### ISSUE TITLE
Feature Request:  Plugin/extension for Visual Studio Code Editor

### ISSUE THREAD

**Issue by DesigningKnights** [oleg-shilo/cs-script#64]
I've been using the Visual Studio Code editor (https://code.visualstudio.com/) for quite some time now.  I would love to see a plugin for cs-script to this.

**Comment by oleg-shilo** [comment]
Isn't it the obvious one? :)

Initially CS-Script integration with popular IDEs was implemented for Visual Studio and Notepad++.  While N++ plugin is the most comprehensive plugin so far (it even includes a debugger) it exhibits two major limitations: 

- Debugging is not as comprehensive as with VS due to the convoluted nature of the underlying MS debugger (MDbg.exe).
- Cannot be run in non-Win environments.

Thus VSCode was the best plugin/extension candidate to overcome these limitations. It was expected to be very simple. As simple as VS extension. The Intellisense services are already there, debugger as well. How hard it could be? However the existing services were implemented in such a way that extending them to load CS-Script projects on fly was more painful than implementing these services from scratch. 

That's why I turned to Sublime Text.  You can use CS-Script with Sublime Text 3 (ST3).  The integration is actually quite good and works on all OSs. Though there is no debugging support: https://github.com/oleg-shilo/cs-script-sublime

Anyway, ST3 plugin effort triggered development of an isolated CS-Script syntaxer/executor module, which in turn simplifies any future integrations with other IDEs/Editors. Thus now I am ready to give it another go and look at the VSCode integration again. Hopefully is also had some API evolution.

Keeping this issue ope. It is a legitimate feature request and it's open fro voting.

**Comment by DesigningKnights** [comment]
Great!  So how does one vote for a feature? :)

**Comment by oleg-shilo** [comment]
Apparently it's not that straight forward.
Vote here: http://poll.gitrun.com/oleg-shilo/cs-script/issues/64

**Comment by oleg-shilo** [comment]
As a side note, I had a look at VSCode on weekend and I have two news. A good and a bad one as usual :o)

Bad one: VSCode execution model still doesn't offer anything better than folder based project structure. Thus VS/XmarinStudio/XCode/MonoDevelop can run a file (e.g. project file)  but VSCode can only run ... a folder. :o(

But the good news is really good. I managed to get a working prototype without the need for the actual extension (only via configuration). It lets one to run a script and even debug it. I am excited about this as I have a way more trust in MonoDebugger than in MDbg (used in N++). May be I am giving ModnoDebuger too much credit but I had to integrate MDbg and I know better than anyone else what it is. I can only compare my work with it to the _Frodo's Journey through the Old Forest_. I got through and alive. But I am not going back...

Anyway, script execution and debugging is done the only things left is to add Intellisense and pack and publish the extension.

The VSCode Intellisense integration with CS-Script is problematic as OmniSharp is also based on a folder structure. But if I a cannot hook into it I can always use my syntaxer from Sublime Text.   

I have started a new GitHub project for the VSCode extension for CS-Script. And will post (in a day or two) the instructions how to configure it for script run/debug so people don't have to wait till the extension is completely ready.

**Comment by oleg-shilo** [comment]
+1

**Comment by oleg-shilo** [comment]
The VSCode extension working prototype has been published: [oleg-shilo/cs-script.vscode](oleg-shilo/cs-script.vscode)

**Comment by oleg-shilo** [comment]
The latest published VSCode CS-Script extension release  can be found on [Marketplace](https://marketplace.visualstudio.com/items?itemName=oleg-shilo.cs-script) or directly from VSCode extensions panel.
