### ISSUE TITLE
Basic types not available to precompilers on linux

### ISSUE THREAD

**Issue by rconde01** [oleg-shilo/cs-script#69]
The following code:

test.cs
```
//css_precompiler Precompiler.cs

using System;

class Test
{
   static void Main(string [] args)
   {
      Console.WriteLine("boo");
   }
}
```

Precompiler.cs
```
using System;
using System.Collections;
using System.Text.RegularExpressions;

public class Precompiler
{
   public static bool Compile(ref string code, string scriptFile, bool isPrimaryScript, Hashtable context)
   {
      Console.WriteLine("zazz");

      return false; //false as the code has not been modified
   }
}
```

On linux this yields an error saying it doesn't know about System.Text.RegularExpressions. This should be in System AFAIK so I'm not sure what the issue is.

**Comment by oleg-shilo** [comment]
Can you just try to add to your precompiler this:
```C#
//css_ref System.dll
```
With the upcoming release it will become a default ref asm but currently on Linux you have to do is manually.

Let me know if it helped.

**Comment by rconde01** [comment]
That results in ...System.dll could not be found (not verbatim...but essentially).

**Comment by oleg-shilo** [comment]
I am currently working on CS-Script C#7 provider for Linux (part of VSCode integration) and I had the very same problem. I solved it by including "System.dll" by default and adding its parent folder as a search dir. 

Because it's done globally by the engine I expect this new version to work right away. Though it is still a few days away from being released. 

If you don't want to wait I can share the preliminary binaries on GitHub. 

Alternatively you can manually add the full path to the System.dll:
```c#
//css_ref <your Mono location>/4.5/System.dll
```

**Comment by rconde01** [comment]
No it's not blocking me...it was just something I noticed when I was fixing the multiple Main problem.

**Comment by oleg-shilo** [comment]
Great. I will keep it open until the next release clears or confirms it.
