### ISSUE TITLE
Error when 'using System;' is not in script

### ISSUE THREAD

**Issue by rconde01** [oleg-shilo/cs-script#75]
Run the following script:

```
class Fix
{
   static void Main(string [] args)
   {
   }
}
```

You get:

```
C# Script execution engine. Version 3.26.1.0.
Copyright (C) 2004-2017 Oleg Shilo.

Error: Specified file could not be compiled.

csscript.CompilerException: c:\Users\rconde\AppData\Local\Temp\CSSCRIPT\Cache\dbg.inject.-1101013751.cs(7,19): error CS0234: The type or namespace name 'RegularExpressions' does not exist in the namespace 'System.Text' (are you missing an assembly reference?)

   at csscript.CSExecutor.ProcessCompilingResult(CompilerResults results, CompilerParameters compilerParams, ScriptParser parser, String scriptFileName, String assemblyFileName, String[] additionalDependencies)
   at csscript.CSExecutor.Compile(String scriptFileName)
   at csscript.CSExecutor.ExecuteImpl()
```

If you add:

`using System;`

the problem goes away.

**Comment by oleg-shilo** [comment]
Yes. It is the expected behavior. 

Your script requires System.dll. Thus you need to either reference it with `//css_ref System.dll` or to let the script engine to to auto-reference by placing `using System;` in your code.
Alternatively you can configure global settings to always reference System.dll.

For more info see: http://www.csscript.net/help/Importing_scripts.html

**Comment by rconde01** [comment]
...but I’m not using regular expressions. So the error is quite weird.

**Comment by oleg-shilo** [comment]
Then may be Regular expression requires System.dll or may be it is only the "dbg" routine from CS-Script runtime. Doesn't matter. Just add the dll or reinstate the "using". Or... as I mentioned configure your environment to reference System.dll always.
