### ISSUE TITLE
CodeDom and interfaces

### ISSUE THREAD

**Issue by Steve0212a** [oleg-shilo/cs-script#81]
I am new to csscript.  I am attempting to use the CodeDom compiler so that the scripts can be debugged.  However, it does not appear that LoadCode<interface name> works when using the CodeDom compiler.  Below is code illustrating the issue.

Am I doing something wrong or is this a bug?

Thanks.

    public interface ITest
    {
        bool Evaluate();
    }

    class Program
    {
        static void Main(string[] args)
        {
            // define the code
            string code = @"
                        public class Script { 
                            public bool Evaluate()
                            {
                                return true;
                            }
                        }
                    ";

            // This works - returns proper values using default compiler, no debugging though
            var scriptWorks1 = CSScript.Evaluator.LoadCode<ITest>(code);
            var r1 = scriptWorks1.Evaluate();

            // set to debug and codedom so we can debug the script
            CSScript.EvaluatorConfig.DebugBuild = true;
            CSScript.EvaluatorConfig.Engine = EvaluatorEngine.CodeDom;

            // This works - returns proper values and allows stepping into the code, no interface specified
            dynamic scriptWorks2 = CSScript.Evaluator.LoadCode(code);
            var r2 = scriptWorks2.Evaluate();

            // this fails with a compile error because of the interface name --> 19	CS0246	The type or namespace name 'Script' could not be found (are you missing a using directive or an assembly reference?)
            var scriptFails = CSScript.Evaluator.LoadCode<ITest>(code);
            var r3 = scriptFails.Evaluate();
        }
    }

**Comment by oleg-shilo** [comment]
The problem is caused by the fact that the script assembly is an in-memory assembly but not a file based assembly. And `LoadCode<ITest>` tires to emit (build) a dynamic proxy class that requires assembly file for building. The simplest solution is to stop loading assemblies from in-memory stream (default behavior) and start using assembly files instead. Add the following line in code and everything will start working:
```C#
CSScript.GlobalSettings.InMemoryAssembly = false;
```
Though, be aware that this has potential side effect, which is the reason why this is not a default setting. The script assembly file will be permanently locked until the app exit (limitation of .NET). 

While it is an intended behavior I do not like the fact that user is not warned about the actual cause of the problem and a potential fix. Thus I am marking your post as an enhancement request.

The commit c19a05c ensures an informative exception is thrown:

![image](https://user-images.githubusercontent.com/16729806/29105846-26de67aa-7d14-11e7-96e9-488c57c987ca.png)


If you prefer to avoid changing `InMemoryAssembly` you can use one of the following work around approaches:
1. Inherit your script class from the interface. This will suppress emitting any proxy objects. 
    ```C#
   string code = @"public class Script : ITest { 
                        public bool Evaluate()
                        {
                            return true;
                        }
                    }";
    ```
2. Use 'dynamic' instead of interface:

    ```C#
    dynamic scriptFails = CSScript.Evaluator
                                  .LoadCode(code);
    var r3 = scriptFails.Evaluate();

**Comment by Steve0212a** [comment]
I will turn off the InMemoryAssembly as the reason I like using the interface is to have a defined interface.  If I use option two, I lose the interface.

Thanks for the quick reply.

**Comment by oleg-shilo** [comment]
`LoadCode<IEvaluatorScriptShowVar>` triggers building a dynamic assembly proxy with the third-party duck-typing module `ObjectCaster`. CS-Script embeds this module. The internals of `LoadCode<T>` are like this:
```C#
object LoadCode<T>(string script)
{
    return LoadCode(script).AlignToInterface<T>(refAsms: null);
}
```
`AlignToInterface` is that ObjectCaster implementation. Problem is that because you are using the simplified "prepacked" form of `LoadCode<T>` you cannot pass an extra ref assembly to the ObjectCaster. Thus you will need to call `LoadCode` and `AlignToInterface` separately.

However, I encourage you to go different way. You completely overlooked option #1 from my previous post. If you inherit your script from `ITest` then you will have no problems what so ever. And you can even keep InMemoryAssembly set to true. 

In fact `LoadCode<T>` expects the object to truly **implement** the interface and only if it doesn't then it tries to create a proxy to it. And this in tern puts some pressure on the developer with controlling the dependencies all the way.

I truly believe option #1 is what you want.

**Comment by Steve0212a** [comment]
You are correct, option #1 is what I want.  I thought I tried it yesterday and had issues with it.  However, it is working today.  Clearly, I did something wrong yesterday.

Thanks

**Comment by oleg-shilo** [comment]
Not a problem. Glad it's all sorted out.
